# Generated by Django 3.2.12 on 2022-08-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_description',
            field=models.TextField(),
        ),
    ]
