# Generated by Django 4.0.7 on 2022-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='installment',
        ),
        migrations.AddField(
            model_name='service',
            name='pay_method',
            field=models.CharField(choices=[('Nəğd', 'Nəğd'), ('Kredit', 'Kredit')], default='Nəğd', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='loan_term',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
