# Generated by Django 4.0.7 on 2022-12-20 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_service_appointment_date_alter_service_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='total_amount_to_be_paid',
        ),
        migrations.RemoveField(
            model_name='servicepayment',
            name='amount_to_be_paid',
        ),
        migrations.RemoveField(
            model_name='servicepayment',
            name='total_amount_to_be_paid',
        ),
        migrations.AddField(
            model_name='service',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_opeartors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='product_quantity',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='remaining_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='service',
            name='service_creditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_creaditors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='service_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='loan_term',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
