# Generated by Django 4.0.7 on 2022-12-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_barcode'),
        ('company', '0008_remove_section_office'),
        ('services', '0007_service_delay_service_delay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproductforcontract',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_product_for_contracts', to='company.company'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='serviceproductforcontract',
            name='product',
        ),
        migrations.AddField(
            model_name='serviceproductforcontract',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='service_for_contracts', to='product.product'),
            preserve_default=False,
        ),
    ]
