# Generated by Django 3.2.9 on 2022-12-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceproductforcontract_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='start_date_of_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
