# Generated by Django 3.2.9 on 2022-12-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_start_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='initial_payment',
            field=models.FloatField(default=0, null=True),
        ),
    ]
