# Generated by Django 3.2.9 on 2022-12-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_initial_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='initial_payment',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
