# Generated by Django 3.2.9 on 2023-01-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_initial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='service_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
