# Generated by Django 3.2.9 on 2023-01-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicepayment_service_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
