# Generated by Django 3.2.9 on 2023-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servicepayment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='service_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
