# Generated by Django 3.2.9 on 2023-01-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicepayment_service_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='service_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
