# Generated by Django 3.2.9 on 2023-02-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_servicepayment_service_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='guarantee',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
