# Generated by Django 3.2.9 on 2023-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_service_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='guarantee',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
