# Generated by Django 3.2.9 on 2023-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_service_guarantee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceproductforcontract',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_serviceproductforcontract', 'Müqaviləyə periodik servis üçün təyin olunmuş məhsullara baxa bilər'), ('add_serviceproductforcontract', 'Müqaviləyə periodik servis üçün məhsullar əlavə edə bilər'), ('change_serviceproductforcontract', 'Müqaviləyə periodik servis üçün təyin olunmuş məhsulların məlumatlarını yeniləyə bilər'), ('delete_serviceproductforcontract', 'Müqaviləyə periodik servis üçün təyin olunmuş məhsulları silə bilər'))},
        ),
    ]
