# Generated by Django 3.2.9 on 2023-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_serviceproductforcontract_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='remaining_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
