# Generated by Django 3.2.9 on 2023-02-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_servicepayment_remaining_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
