# Generated by Django 3.2.9 on 2023-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_service_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='initial_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='remaining_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='remaining_debt',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='service_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='service_paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
