version: "3.9"

services:
  web:
    build: ./src
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --timeout 300 --worker-class=gevent --worker-connections=1000 --workers=5 core.wsgi"
    volumes:
      - ./src/core:/app/core
      - ./src/media:/app/media
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    depends_on:
      - redis
      - db
    env_file:
      - ./src/.env/
    environment:
      - STATIC_ROOT=/app/static
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
      - MEDIA_URL=/app/media/

  db:
    image: library/postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - 54035:5432
    volumes:
      - ./src/db:/var/lib/postgresql/data/
    env_file:
      - ./src/.env/
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7.0.0-alpine
    restart: unless-stopped
    ports:
      - 63079:6379
    expose:
      - "6379"
    env_file:
      - ./src/.env/
    environment:
     - REDIS_HOST=${REDIS_HOST}

  worker:
    build: ./src
    restart: unless-stopped
    command: celery -A core worker --beat --scheduler django --loglevel=info --concurrency=8 -O fair -P prefork -n core
    env_file:
      - ./src/.env/
    environment:
     - CELERY_BROKER=${CELERY_BROKER}
     - RESULT_BACKEND=${CELERY_BACKEND}
     - REDIS_HOST=${REDIS_HOST}
     - REDIS_PORT=${REDIS_PORT}
     - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
      - redis
    depends_on:
      - web
      - redis
      - db

  celery_beat:
    build: ./src
    command: celery -A core beat -l info
    restart: unless-stopped
    volumes:
      - ./src:/app/
    env_file:
      - ./src/.env/
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER=${CELERY_BROKER}
      - RESULT_BACKEND=${CELERY_BACKEND}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - web
      - redis
      - db