# Generated by Django 3.2.12 on 2022-09-06 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('tapşırıq', 'tapşırıq'), ('elan', 'elan')], default=None, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('İcra edilir', 'İcra edilir'), ('Gecikir', 'Gecikir'), ('Tamamlandı', 'Tamamlandı')], default='İcra edilir', max_length=50)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='company.vezifeler')),
                ('tag', models.ManyToManyField(related_name='tasks', to='company.Tag')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_taskmanager', 'Tapşırıqlara baxa bilər'), ('add_taskmanager', 'Tapşırıq əlavə edə bilər'), ('change_taskmanager', 'Tapşırığı yeniləyə bilər'), ('delete_taskmanager', 'Tapşırığı silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
