# Generated by Django 4.0.7 on 2022-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='old_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
