# Generated by Django 3.2.12 on 2022-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20220906_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
