# Generated by Django 3.2.12 on 2022-09-08 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20220907_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
