# Generated by Django 3.2.12 on 2022-09-06 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_taskmanager_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
