# Generated by Django 3.2.12 on 2022-09-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_taskmanager_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
