# Generated by Django 3.2.12 on 2022-09-16 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_taskmanager_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskrequest',
            name='change_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertaskrequest',
            name='new_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
