# Generated by Django 3.2.12 on 2022-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_taskmanager_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/task-documents/%Y/%m/%d/'),
        ),
    ]
