# Generated by Django 3.2.12 on 2022-09-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_taskmanager_task_manage_employe_557437_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskmanager',
            name='task_manage_employe_557437_idx',
        ),
    ]
