# Generated by Django 4.0.7 on 2022-09-20 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_department_options'),
        ('task_manager', '0007_remove_taskmanager_task_manage_employe_557437_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmanager',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='type',
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='company.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_advertisement', 'Elanlara baxa bilər'), ('add_advertisement', 'Elan əlavə edə bilər'), ('change_advertisement', 'Elanı yeniləyə bilər'), ('delete_advertisement', 'Elanı silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
