# Generated by Django 4.0.7 on 2022-09-20 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0008_rename_description_taskmanager_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertaskrequest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gettin_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
