# Generated by Django 4.0.7 on 2022-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_advertisement_creator_taskmanager_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskrequest',
            name='is_accept',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
