# Generated by Django 4.0.7 on 2022-09-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_alter_usertaskrequest_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskrequest',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
