# Generated by Django 4.0.7 on 2022-10-06 11:29

import core.image_validator
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_office_unique name for your office constraint'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.AlterField(
            model_name='user',
            name='back_photo_of_ID',
            field=models.ImageField(blank=True, help_text='Şəxsiyyət vəsiqəsi 2', null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Şirkət', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('xidməti müqavilə', 'xidməti müqavilə'), ('əmək müqaviləsi', 'əmək müqaviləsi')], default=None, help_text='Müqavilə növü', max_length=50, null=True, verbose_name='Müqavilə növü'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Departament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dismissal_date',
            field=models.DateField(blank=True, help_text='İşdən ayrılma tarixi', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_license_photo',
            field=models.ImageField(blank=True, help_text='Sürücülük vəsiqəsi', null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_status',
            field=models.ForeignKey(blank=True, help_text='İşçi statusu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='account.employeestatus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(help_text='Adı Soyadı Ata adı', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, help_text='Qeyd', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Ofis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.office'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_1',
            field=models.CharField(help_text='Telefon 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_2',
            field=models.CharField(blank=True, help_text='Telefon 2', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_ID',
            field=models.ImageField(blank=True, help_text='Şəxsiyyət vəsiqəsi', null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Vəzifə', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profil şəkli', null=True, upload_to='media/profile/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(blank=True, default=0, help_text='Ə/H', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_style',
            field=models.CharField(choices=[('aylıq', 'aylıq'), ('günlük', 'günlük'), ('həftəlik', 'həftəlik'), ('fix', 'fix')], default='aylıq', help_text='Ə/H ödəmə üslubu', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Şöbə', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date_of_work',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='İşə başlama tarixi', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervizor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.OneToOneField(blank=True, default=None, help_text='Komanda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.team'),
        ),
    ]
