# Generated by Django 4.0.7 on 2022-10-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_alter_commissioninstallment_options_and_more'),
        ('account', '0005_user_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='salary.commission'),
        ),
    ]
