# Generated by Django 4.0.7 on 2022-11-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_contract_date_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contract_type',
            new_name='register_type',
        ),
    ]
