# Generated by Django 4.0.7 on 2022-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(blank=True, default=0, help_text='Ə/H', null=True),
        ),
    ]
