# Generated by Django 3.2.9 on 2023-01-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_section_office'),
        ('account', '0015_alter_user_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='customer',
            name='fin_code',
            field=models.CharField(default=1234567, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Şöbə', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.section'),
        ),
    ]
