# Generated by Django 3.2.9 on 2023-01-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_customer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Deaktiv', 'Deaktiv')], default='Aktiv', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_employeeactivity', 'Mövcud işçi müqavilə tarixçələrinə bilər'), ('add_employeeactivity', 'İşçi müqavilə tarixçəsi əlavə edə bilər'), ('change_employeeactivity', 'İşçi müqavilə tarixçəsi məlumatlarını yeniləyə bilər'), ('delete_employeeactivity', 'İşçi müqavilə tarixçəsi silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
