# Generated by Django 3.2.9 on 2023-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20230128_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='group_tye',
            new_name='group_type',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='function_type',
            field=models.CharField(blank=True, choices=[('Görmək', 'Görmək'), ('Dəyişmək', 'Dəyişmək'), ('Əlavə etmək', 'Əlavə etmək'), ('Silmək', 'Silmək')], max_length=200, null=True),
        ),
    ]
