# Generated by Django 3.2.9 on 2023-01-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20230128_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuPagination',
            new_name='MenuPermission',
        ),
    ]
