# Generated by Django 3.2.9 on 2023-01-29 12:58

import core.image_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_rename_menupagination_menupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
