# Generated by Django 3.2.9 on 2023-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_permission',
            field=models.ManyToManyField(blank=True, related_name='employees', to='account.AppPermission'),
        ),
    ]
