# Generated by Django 3.2.9 on 2023-02-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_user_app_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fin_code',
            field=models.CharField(default=1234567, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
