# Generated by Django 3.2.9 on 2023-02-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20230203_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
