# Generated by Django 3.2.9 on 2023-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20230209_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
