# Generated by Django 3.2.9 on 2023-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermission',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
