# Generated by Django 3.2.12 on 2022-09-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirketdenOfislereTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField(default=0)),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('qalan_mebleg', models.FloatField(blank=True, default=0)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('ofis_kassa', models.ManyToManyField(related_name='shirketden_ofise_transfer', to='cashbox.OfisKassa')),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_ofise_transfer', to='cashbox.shirketkassa')),
                ('transfer_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shirket_ofis_transfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_shirketdenofisleretransfer', 'Mövcud şirkətdən ofislərə olan transferlərə baxa bilər'), ('add_shirketdenofisleretransfer', 'Şirkətdən ofislərə transfer edə bilər'), ('change_shirketdenofisleretransfer', 'Şirkətdən ofislərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_shirketdenofisleretransfer', 'Şirkətdən ofislərə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ShirketdenHoldingeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField(default=0)),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('qalan_mebleg', models.FloatField(blank=True, default=0)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='cashbox.holdingkassa')),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='cashbox.shirketkassa')),
                ('transfer_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shirket_holding_transfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_shirketdenholdingetransfer', 'Mövcud şirkətdən holdinqlərə olan transferlərə baxa bilər'), ('add_shirketdenholdingetransfer', 'Şirkətdən holdinqlərə transfer edə bilər'), ('change_shirketdenholdingetransfer', 'Şirkətdən holdinqlərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_shirketdenholdingetransfer', 'Şirkətdən holdinqlərə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OfisdenShirketeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField(default=0)),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('qalan_mebleg', models.FloatField(blank=True, default=0)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('ofis_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='cashbox.ofiskassa')),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='cashbox.shirketkassa')),
                ('transfer_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ofis_shirket_transfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_ofisdenshirketetransfer', 'Mövcud ofisdən şirkətə olan transferlərə baxa bilər'), ('add_ofisdenshirketetransfer', 'Ofisdən şirkətə transfer edə bilər'), ('change_ofisdenshirketetransfer', 'Ofisdən şirkətə olan transfer məlumatlarını yeniləyə bilər'), ('delete_ofisdenshirketetransfer', 'Ofisdən şirkətə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingdenShirketlereTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField(default=0)),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('qalan_mebleg', models.FloatField(blank=True, default=0)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdingden_shirkete_transfer', to='cashbox.holdingkassa')),
                ('shirket_kassa', models.ManyToManyField(related_name='holdingden_shirkete_transfer', to='cashbox.ShirketKassa')),
                ('transfer_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_holding_shirket_transfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_holdingdenshirketleretransfer', 'Mövcud holdinqdən şirkətlərə olan transferlərə baxa bilər'), ('add_holdingdenshirketleretransfer', 'Holdinqdən şirkətlərə transfer edə bilər'), ('change_holdingdenshirketleretransfer', 'Holdinqdən şirkətlərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_holdingdenshirketleretransfer', 'Holdinqdən şirkətlərə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
