# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingdenshirketleretransfer',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_holdingdenshirketleretransfer', 'Mövcud holdinqdən şirkətlərə olan transferlərə baxa bilər'), ('add_holdingdenshirketleretransfer', 'Holdinqdən şirkətlərə transfer edə bilər'), ('change_holdingdenshirketleretransfer', 'Holdinqdən şirkətlərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_holdingdenshirketleretransfer', 'Holdinqdən şirkətlərə olan transfer məlumatlarını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='ofisdenshirketetransfer',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_ofisdenshirketetransfer', 'Mövcud ofisdən şirkətə olan transferlərə baxa bilər'), ('add_ofisdenshirketetransfer', 'Ofisdən şirkətə transfer edə bilər'), ('change_ofisdenshirketetransfer', 'Ofisdən şirkətə olan transfer məlumatlarını yeniləyə bilər'), ('delete_ofisdenshirketetransfer', 'Ofisdən şirkətə olan transfer məlumatlarını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirketdenholdingetransfer',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_shirketdenholdingetransfer', 'Mövcud şirkətdən holdinqlərə olan transferlərə baxa bilər'), ('add_shirketdenholdingetransfer', 'Şirkətdən holdinqlərə transfer edə bilər'), ('change_shirketdenholdingetransfer', 'Şirkətdən holdinqlərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_shirketdenholdingetransfer', 'Şirkətdən holdinqlərə olan transfer məlumatlarını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirketdenofisleretransfer',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_shirketdenofisleretransfer', 'Mövcud şirkətdən ofislərə olan transferlərə baxa bilər'), ('add_shirketdenofisleretransfer', 'Şirkətdən ofislərə transfer edə bilər'), ('change_shirketdenofisleretransfer', 'Şirkətdən ofislərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_shirketdenofisleretransfer', 'Şirkətdən ofislərə olan transfer məlumatlarını silə bilər'))},
        ),
    ]
