# Generated by Django 4.0.7 on 2022-11-03 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_position_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(auto_now=True)),
                ('transfer_note', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_in_office_transfer', to='company.company')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiving_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_offices_in_office_transfers', to='company.office')),
                ('sending_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_offices_in_office_transfers', to='company.office')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_companytransfer', 'Mövcud şirkət transferlərə baxa bilər'), ('add_companytransfer', 'Şirkət transfer edə bilər'), ('change_companytransfer', 'Şirkət transfer məlumatlarını yeniləyə bilər'), ('delete_companytransfer', 'Şirkət transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(auto_now=True)),
                ('transfer_note', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiving_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_companies_in_holding_transfers', to='company.company')),
                ('sending_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_companies_in_holding_transfers', to='company.company')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_holdingtransfer', 'Mövcud holdinq transferlərə baxa bilər'), ('add_holdingtransfer', 'Holdinq transfer edə bilər'), ('change_holdingtransfer', 'Holdinq transfer məlumatlarını yeniləyə bilər'), ('delete_holdingtransfer', 'Holdinq transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CompanyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(auto_now=True)),
                ('transfer_note', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_in_company_transfer', to='company.company')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiving_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_offices_in_company_transfers', to='company.office')),
                ('sending_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_offices_in_company_transfers', to='company.office')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_companytransfer', 'Mövcud şirkət transferlərə baxa bilər'), ('add_companytransfer', 'Şirkət transfer edə bilər'), ('change_companytransfer', 'Şirkət transfer məlumatlarını yeniləyə bilər'), ('delete_companytransfer', 'Şirkət transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
