# Generated by Django 4.0.7 on 2022-11-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_officetransfer_holdingtransfer_companytransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferfromcompanytooffices',
            name='company_cashbox',
        ),
        migrations.RemoveField(
            model_name='transferfromcompanytooffices',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='transferfromcompanytooffices',
            name='office_cashbox',
        ),
        migrations.RemoveField(
            model_name='transferfromholdingtocompany',
            name='company_cashbox',
        ),
        migrations.RemoveField(
            model_name='transferfromholdingtocompany',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='transferfromholdingtocompany',
            name='holding_cashbox',
        ),
        migrations.RemoveField(
            model_name='transferfromofficetocompany',
            name='company_cashbox',
        ),
        migrations.RemoveField(
            model_name='transferfromofficetocompany',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='transferfromofficetocompany',
            name='office_cashbox',
        ),
        migrations.AlterModelOptions(
            name='officetransfer',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_officetransfer', 'Mövcud ofis transferlərə baxa bilər'), ('add_officetransfer', 'Ofis transfer edə bilər'), ('change_officetransfer', 'Ofis transfer məlumatlarını yeniləyə bilər'), ('delete_officetransfer', 'Ofis transfer məlumatlarını silə bilər'))},
        ),
        migrations.RemoveField(
            model_name='companytransfer',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='holdingtransfer',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='remaining_amount',
        ),
        migrations.DeleteModel(
            name='TransferFromCompanyToHolding',
        ),
        migrations.DeleteModel(
            name='TransferFromCompanyToOffices',
        ),
        migrations.DeleteModel(
            name='TransferFromHoldingToCompany',
        ),
        migrations.DeleteModel(
            name='TransferFromOfficeToCompany',
        ),
    ]
