# Generated by Django 4.0.7 on 2022-09-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officecashbox',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_officecashbox', 'Mövcud ofis kassalara baxa bilər'), ('add_officecashbox', 'Ofis kassa əlavə edə bilər'), ('change_officecashbox', 'Ofis kassa məlumatlarını yeniləyə bilər'), ('delete_officecashbox', 'Ofis kassa silə bilər'))},
        ),
    ]
