# Generated by Django 4.0.7 on 2022-11-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_alter_officecashbox_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycashbox',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holdingcashbox',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='officecashbox',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
