# Generated by Django 4.0.7 on 2022-11-05 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0003_alter_companycashbox_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingCashboxOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=None)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_cashbox_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_holdingcashboxoperation', 'Mövcud holdinq kassa əməliyyatlarına baxa bilər'), ('add_holdingcashboxoperation', 'Holdinq kassa əməliyyatı əlavə edə bilər'), ('change_holdingcashboxoperation', 'Holdinq kassa əməliyyatı məlumatlarını yeniləyə bilər'), ('delete_holdingcashboxoperation', 'Holdinq kassa əməliyyatı məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
