# Generated by Django 4.0.7 on 2022-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0007_cashflow_customer_alter_cashflow_operation_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycashbox',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companycashbox',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holdingcashbox',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='holdingcashbox',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officecashbox',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='officecashbox',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
