# Generated by Django 4.0.7 on 2022-11-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0010_companycashboxoperation_personal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='company_initial_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='company_subsequent_balance',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='holding_initial_balance',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='holding_subsequent_balance',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='office_initial_balance',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='office_subsequent_balance',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='subsequent_balance',
        ),
    ]
