# Generated by Django 3.2.9 on 2023-01-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0015_costtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycashboxoperation',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbox.costtype'),
        ),
        migrations.AddField(
            model_name='holdingcashboxoperation',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbox.costtype'),
        ),
    ]
