# Generated by Django 3.2.9 on 2023-01-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0016_auto_20230124_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='cashbox.costtype'),
        ),
    ]
