# Generated by Django 3.2.9 on 2023-01-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0017_cashflow_cost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='operation_style',
            field=models.CharField(blank=True, choices=[('MƏDAXİL', 'MƏDAXİL'), ('MƏXARİC', 'MƏXARİC'), ('KORREKSİYA', 'KORREKSİYA')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companycashboxoperation',
            name='operation',
            field=models.CharField(choices=[('MƏDAXİL', 'MƏDAXİL'), ('MƏXARİC', 'MƏXARİC'), ('KORREKSİYA', 'KORREKSİYA')], default='MƏDAXİL', max_length=150),
        ),
        migrations.AlterField(
            model_name='holdingcashboxoperation',
            name='operation',
            field=models.CharField(choices=[('MƏDAXİL', 'MƏDAXİL'), ('MƏXARİC', 'MƏXARİC'), ('KORREKSİYA', 'KORREKSİYA')], default='MƏDAXİL', max_length=150),
        ),
    ]
