# Generated by Django 3.2.9 on 2023-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0018_auto_20230130_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycashbox',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_companycashbox', 'Mövcud şirkət kassalara baxa bilər'), ('add_companycashbox', 'Şirkət kassa əlavə edə bilər'), ('change_companycashbox', 'Şirkət kassa məlumatlarını yeniləyə bilər'), ('delete_companycashbox', 'Şirkət kassa silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='costtype',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_costtype', 'Mövcud xərc növlərinə baxa bilər'), ('add_costtype', 'Xərc növü əlavə edə bilər'), ('change_costtype', 'Xərc növü məlumatlarını yeniləyə bilər'), ('delete_costtype', 'Xərc növü məlumatlarını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='holdingcashbox',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_holdingcashbox', 'Mövcud holdinq kassalara baxa bilər'), ('add_holdingcashbox', 'Holdinq kassa əlavə edə bilər'), ('change_holdingcashbox', 'Holdinq kassa məlumatlarını yeniləyə bilər'), ('delete_holdingcashbox', 'Holdinq kassa silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='officecashbox',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_officecashbox', 'Mövcud ofis kassalara baxa bilər'), ('add_officecashbox', 'Ofis kassa əlavə edə bilər'), ('change_officecashbox', 'Ofis kassa məlumatlarını yeniləyə bilər'), ('delete_officecashbox', 'Ofis kassa silə bilər'))},
        ),
    ]
