# Generated by Django 4.0.7 on 2022-10-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='amount',
        ),
    ]
