# Generated by Django 4.0.7 on 2022-10-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_remove_advancepayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='half_month_salary',
        ),
    ]
