# Generated by Django 4.0.7 on 2022-10-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_remove_advancepayment_half_month_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
