# Generated by Django 4.0.7 on 2022-10-14 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0004_advancepayment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPunishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_punishment', 'Mövcud cərimələrə baxa bilər'), ('add_punishment', 'Cərimə əlavə edə bilər'), ('change_punishment', 'Cərimə məlumatlarını yeniləyə bilər'), ('delete_punishment', 'Cərimə silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
