# Generated by Django 4.0.7 on 2022-10-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_salarypunishment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paysalary',
            old_name='installment',
            new_name='salary_date',
        ),
    ]
