# Generated by Django 4.0.7 on 2022-10-22 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_rename_installment_paysalary_salary_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('start_month', models.PositiveIntegerField(default=0)),
                ('end_month', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_monthrange', 'Mövcud ay aralıqlarına baxa bilər'), ('add_monthrange', 'Ay aralığı əlavə edə bilər'), ('change_monthrange', 'Ay aralığı məlumatlarını yeniləyə bilər'), ('delete_monthrange', 'Ay aralığı silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SaleRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('start_count', models.PositiveIntegerField(default=0)),
                ('end_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_salerange', 'Mövcud satış aralığı baxa bilər'), ('add_salerange', 'Satış Aralığı əlavə edə bilər'), ('change_salerange', 'Satış Aralığı məlumatlarını yeniləyə bilər'), ('delete_salerange', 'Satış Aralığı silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CommissionSaleRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.FloatField(default=0)),
                ('sale_type', models.CharField(choices=[('fix', 'fix'), ('say', 'say')], default='fix', max_length=50)),
                ('sale_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_ranges', to='salary.salerange')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.FloatField(default=0)),
                ('month_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_ranges', to='salary.monthrange')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_name', models.CharField(max_length=200)),
                ('for_office', models.FloatField(blank=True, default=0)),
                ('cash', models.FloatField(blank=True, default=0)),
                ('for_team', models.FloatField(blank=True, default=0)),
                ('for_sale_range', models.ManyToManyField(related_name='for_sale_ranges', to='salary.commissionsalerange')),
                ('installment', models.ManyToManyField(related_name='installments', to='salary.commissioninstallment')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_commission', 'Mövcud komissiyalara baxa bilər'), ('add_commission', 'Komissiya əlavə edə bilər'), ('change_commission', 'Komissiya məlumatlarını yeniləyə bilər'), ('delete_commission', 'Komissiya silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
