# Generated by Django 4.0.7 on 2022-10-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_monthrange_salerange_commissionsalerange_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissioninstallment',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_commissioninstallment', 'Mövcud komissiya kreditlərinə baxa bilər'), ('add_commissioninstallment', 'Komissya kredit əlavə edə bilər'), ('change_commissioninstallment', 'Komissya kredit məlumatlarını yeniləyə bilər'), ('delete_commissioninstallment', 'Komissya kredit silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='commissionsalerange',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_commissionsalerange', 'Mövcud komissiya satış aralığı baxa bilər'), ('add_commissionsalerange', 'Komissya satış aralığı əlavə edə bilər'), ('change_commissionsalerange', 'Komissya satış aralığı məlumatlarını yeniləyə bilər'), ('delete_commissionsalerange', 'Komissya satış aralığı silə bilər'))},
        ),
        migrations.RemoveField(
            model_name='commissioninstallment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='commissionsalerange',
            name='title',
        ),
    ]
