# Generated by Django 4.0.7 on 2022-10-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_alter_commissioninstallment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='for_office',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='for_team',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
