# Generated by Django 4.0.7 on 2022-10-25 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contractchange_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0010_alter_monthrange_end_month_alter_salerange_end_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenCommissionAfterSignContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_commissions', to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditorPrim',
        ),
        migrations.RemoveField(
            model_name='manager1primnew',
            name='position',
        ),
        migrations.RemoveField(
            model_name='manager1primnew',
            name='prim_status',
        ),
        migrations.RemoveField(
            model_name='manager1primnew',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manager2prim',
            name='position',
        ),
        migrations.RemoveField(
            model_name='manager2prim',
            name='prim_status',
        ),
        migrations.RemoveField(
            model_name='manager2prim',
            name='product',
        ),
        migrations.RemoveField(
            model_name='officeleaderprim',
            name='position',
        ),
        migrations.RemoveField(
            model_name='officeleaderprim',
            name='prim_status',
        ),
        migrations.RemoveField(
            model_name='officeleaderprim',
            name='product',
        ),
        migrations.AddField(
            model_name='commission',
            name='creditor_per_cent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='GroupLeaderPrimNew',
        ),
        migrations.DeleteModel(
            name='Manager1PrimNew',
        ),
        migrations.DeleteModel(
            name='Manager2Prim',
        ),
        migrations.DeleteModel(
            name='OfficeLeaderPrim',
        ),
    ]
