# Generated by Django 4.0.7 on 2022-10-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_givencommissionaftersigncontract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='for_sale_range',
            field=models.ManyToManyField(related_name='commissions', to='salary.commissionsalerange'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='installment',
            field=models.ManyToManyField(related_name='commissions', to='salary.commissioninstallment'),
        ),
    ]
