# Generated by Django 4.0.7 on 2022-11-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_alter_commission_for_sale_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryview',
            name='commission_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
