# Generated by Django 4.0.7 on 2022-11-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_salaryview_commission_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salaryview',
            index=models.Index(fields=['employee', 'sale_quantity', 'sales_amount', 'final_salary', 'date'], name='salary_sala_employe_aa6d9b_idx'),
        ),
    ]
