# Generated by Django 4.0.7 on 2022-11-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0021_salaryviewexport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryviewexport',
            old_name='file',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='salaryviewexport',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
