# Generated by Django 4.0.7 on 2022-11-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0027_advancepayment_salary_date_bonus_salary_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.FloatField(default=0)),
                ('advance_payment', models.FloatField(default=0)),
                ('salary_deduction', models.FloatField(default=0)),
                ('salary_punishment', models.FloatField(default=0)),
                ('salary_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_histories', to='salary.salaryview')),
            ],
        ),
    ]
