# Generated by Django 4.0.7 on 2022-11-24 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0028_employeeactivityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeactivityhistory',
            name='activity_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
