# Generated by Django 3.2.9 on 2023-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0036_alter_advancepayment_amount_alter_bonus_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancepayment',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_advancepayment', 'Mövcud avanslara baxa bilər'), ('add_advancepayment', 'Avans əlavə edə bilər'), ('change_advancepayment', 'Avans məlumatlarını yeniləyə bilər'), ('delete_advancepayment', 'Avans silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_bonus', 'Mövcud bonuslara baxa bilər'), ('add_bonus', 'Bonus əlavə edə bilər'), ('change_bonus', 'Bonus məlumatlarını yeniləyə bilər'), ('delete_bonus', 'Bonus silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_commission', 'Mövcud komissiyalara baxa bilər'), ('add_commission', 'Komissiya əlavə edə bilər'), ('change_commission', 'Komissiya məlumatlarını yeniləyə bilər'), ('delete_commission', 'Komissiya silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='commissioninstallment',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_commissioninstallment', 'Mövcud komissiya kreditlərinə baxa bilər'), ('add_commissioninstallment', 'Komissya kredit əlavə edə bilər'), ('change_commissioninstallment', 'Komissya kredit məlumatlarını yeniləyə bilər'), ('delete_commissioninstallment', 'Komissya kredit silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='commissionsalerange',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_commissionsalerange', 'Mövcud komissiya satış aralığı baxa bilər'), ('add_commissionsalerange', 'Komissya satış aralığı əlavə edə bilər'), ('change_commissionsalerange', 'Komissya satış aralığı məlumatlarını yeniləyə bilər'), ('delete_commissionsalerange', 'Komissya satış aralığı silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='monthrange',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_monthrange', 'Mövcud ay aralıqlarına baxa bilər'), ('add_monthrange', 'Ay aralığı əlavə edə bilər'), ('change_monthrange', 'Ay aralığı məlumatlarını yeniləyə bilər'), ('delete_monthrange', 'Ay aralığı silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='paysalary',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_paysalary', 'Mövcud maaş ödəmələrinə baxa bilər'), ('add_paysalary', 'Maaş ödəmə əlavə edə bilər'), ('change_paysalary', 'Maaş ödəmə məlumatlarını yeniləyə bilər'), ('delete_paysalary', 'Maaş ödəmə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='salarydeduction',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_salarydeduction', 'Mövcud kəsintilərə baxa bilər'), ('add_salarydeduction', 'Kəsinti əlavə edə bilər'), ('change_salarydeduction', 'Kəsinti məlumatlarını yeniləyə bilər'), ('delete_salarydeduction', 'Kəsinti silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='salarypunishment',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_punishment', 'Mövcud cərimələrə baxa bilər'), ('add_punishment', 'Cərimə əlavə edə bilər'), ('change_punishment', 'Cərimə məlumatlarını yeniləyə bilər'), ('delete_punishment', 'Cərimə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='salerange',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_salerange', 'Mövcud satış aralığı baxa bilər'), ('add_salerange', 'Satış Aralığı əlavə edə bilər'), ('change_salerange', 'Satış Aralığı məlumatlarını yeniləyə bilər'), ('delete_salerange', 'Satış Aralığı silə bilər'))},
        ),
    ]
