# Generated by Django 3.2.9 on 2023-02-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0037_auto_20230203_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='givencommissionaftersigncontract',
            old_name='amount',
            new_name='cash',
        ),
        migrations.RemoveField(
            model_name='givencommissionaftersigncontract',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='givencommissionaftersigncontract',
            name='user',
        ),
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='for_installment_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='for_office',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='for_sale_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='for_team',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='salary_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_commissions', to='salary.salaryview'),
        ),
    ]
