# Generated by Django 3.2.9 on 2023-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0039_givencommissionaftersigncontract_for_fix_sale_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='sale_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='sales_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
