# Generated by Django 3.2.9 on 2023-02-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0040_auto_20230208_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GivenCommissionAfterSignContract',
        ),
    ]
