# Generated by Django 4.0.7 on 2022-11-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_employeeholiday_employeeholidayhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeholiday',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='holiday.employeeholidayhistory'),
        ),
    ]
