# Generated by Django 4.0.7 on 2022-11-26 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_alter_employeeholiday_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkingday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
