# Generated by Django 4.0.7 on 2022-11-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0004_employeeworkingday_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeholiday',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_employeeholiday', 'Mövcud tətillərə baxa bilər'),)},
        ),
        migrations.AlterModelOptions(
            name='employeeholidayhistory',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_employeeholidayhistory', 'Mövcud tətil tarixçələrinə baxa bilər'), ('change_employeeholidayhistory', 'Tətil tarixçəsi məlumatlarını yeniləyə bilər'), ('delete_employeeholidayhistory', 'Tətil tarixçəsi silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='employeeworkingday',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_employeeworkingday', 'İşçilərin iş qrafikinə baxa bilər'),)},
        ),
        migrations.AlterModelOptions(
            name='holidayoperation',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('add_holidayoperation', 'Tətil əlavə etmə əməliyyatı edə bilər'),)},
        ),
    ]
