# Generated by Django 4.0.7 on 2022-11-27 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holiday', '0005_alter_employeeholiday_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDayOffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_employeedayoffhistory', 'Mövcud icazə tarixçələrinə baxa bilər'), ('change_employeedayoffhistory', 'İcazə tarixçəsi məlumatlarını yeniləyə bilər'), ('delete_employeedayoffhistory', 'İcazə tarixçəsi silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDayOffOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.CharField(max_length=350)),
                ('is_paid', models.BooleanField(default=False)),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('add_employeedayoffoperation', 'İcazə əlavə etmə əməliyyatı edə bilər'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_off_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to=settings.AUTH_USER_MODEL)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='holiday.employeedayoffhistory')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_employeedayoff', 'Mövcud icazələrə baxa bilər'),),
                'default_permissions': [],
            },
        ),
    ]
