# Generated by Django 4.0.7 on 2022-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0009_employeedayoffhistory_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedayoff',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
