# Generated by Django 4.0.7 on 2022-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0011_alter_employeedayoff_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedayoff',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
