# Generated by Django 4.0.7 on 2022-12-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0012_alter_employeedayoff_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayoperation',
            name='holiday_date',
            field=models.CharField(max_length=800),
        ),
    ]
