# Generated by Django 3.2.9 on 2023-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0014_alter_employeedayoffoperation_day_off_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedayoff',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
