# Generated by Django 3.2.12 on 2022-07-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mehsullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsulun_adi', models.CharField(max_length=300)),
                ('qiymet', models.FloatField()),
                ('is_hediyye', models.BooleanField(default=False)),
                ('kartric_novu', models.CharField(blank=True, choices=[('KARTRIC6AY', 'KARTRIC6AY'), ('KARTRIC12AY', 'KARTRIC12AY'), ('KARTRIC18AY', 'KARTRIC18AY'), ('KARTRIC24AY', 'KARTRIC24AY')], default=None, max_length=50, null=True)),
                ('shirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_mehsul', to='company.shirket')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
