# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mehsullar',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_mehsullar', 'Mövcud məhsullara baxa bilər'), ('add_mehsullar', 'Məhsul əlavə edə bilər'), ('change_mehsullar', 'Məhsul məlumatlarını yeniləyə bilər'), ('delete_mehsullar', 'Məhsul silə bilər'))},
        ),
    ]
