# Generated by Django 4.0.7 on 2022-09-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hediyye',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
