# Generated by Django 4.0.7 on 2022-09-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_department_company_department_holding'),
        ('product', '0002_remove_product_is_hediyye_alter_product_is_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_product', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_name', 'category', 'company'), name='unique product name for your constraint'),
        ),
    ]
