# Generated by Django 4.0.7 on 2022-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
