# Generated by Django 4.0.7 on 2022-09-27 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('İcra edilir', 'İcra edilir'), ('Gecikir', 'Gecikir'), ('Tamamlandı', 'Tamamlandı')], default='İcra edilir', max_length=50)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gettin_tasks', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='company.position')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_taskmanager', 'Tapşırıqlara baxa bilər'), ('add_taskmanager', 'Tapşırıq əlavə edə bilər'), ('change_taskmanager', 'Tapşırığı yeniləyə bilər'), ('delete_taskmanager', 'Tapşırığı silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='UserTaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('change_date', models.DateField(auto_now_add=True)),
                ('new_date', models.DateField()),
                ('is_accept', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_requests', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='task_manager.taskmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_advertisements', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='company.position')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_advertisement', 'Elanlara baxa bilər'), ('add_advertisement', 'Elan əlavə edə bilər'), ('change_advertisement', 'Elanı yeniləyə bilər'), ('delete_advertisement', 'Elanı silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
