# Generated by Django 4.0.7 on 2022-10-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_office_unique name for your office constraint'),
        ('task_manager', '0002_taskmanager_old_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='position',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, related_name='advertisements', to='company.position'),
        ),
    ]
