# Generated by Django 3.2.9 on 2023-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_advertisement_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_advertisement', 'Elanlara baxa bilər'), ('add_advertisement', 'Elan əlavə edə bilər'), ('change_advertisement', 'Elanı yeniləyə bilər'), ('delete_advertisement', 'Elanı silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='taskmanager',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_taskmanager', 'Tapşırıqlara baxa bilər'), ('add_taskmanager', 'Tapşırıq əlavə edə bilər'), ('change_taskmanager', 'Tapşırığı yeniləyə bilər'), ('delete_taskmanager', 'Tapşırığı silə bilər'))},
        ),
    ]
