# Generated by Django 3.2.12 on 2022-07-29 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kredit', models.BooleanField(blank=True, default=False)),
                ('kredit_muddeti', models.IntegerField(blank=True, default=0)),
                ('endirim', models.FloatField(blank=True, default=0)),
                ('servis_tarix', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('yerine_yetirildi', models.BooleanField(default=False)),
                ('servis_qiymeti', models.FloatField(blank=True, default=0)),
                ('ilkin_odenis', models.FloatField(blank=True, default=0)),
                ('odenilecek_umumi_mebleg', models.FloatField(blank=True, default=0)),
                ('operator_tesdiq', models.BooleanField(default=False)),
                ('qeyd', models.TextField(blank=True, default='')),
                ('is_auto', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('mehsullar', models.ManyToManyField(related_name='servis_mehsul', to='contract.Muqavile')),
                ('muqavile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servis_muqavile', to='contract.muqavile')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ServisOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odenilecek_umumi_mebleg', models.FloatField(blank=True, default=0)),
                ('odenilecek_mebleg', models.FloatField(blank=True, default=0)),
                ('odendi', models.BooleanField(default=False)),
                ('odeme_tarix', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('servis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servis_odeme', to='services.servis')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
