# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servis_mehsullar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servis',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_servis', 'Mövcud servislərə baxa bilər'), ('add_servis', 'Servis əlavə edə bilər'), ('change_servis', 'Servis məlumatlarını yeniləyə bilər'), ('delete_servis', 'Servis silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='servisodeme',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_servisodeme', 'Mövcud servis ödəmələrinə baxa bilər'), ('add_servisodeme', 'Servis ödəmə əlavə edə bilər'), ('change_servisodeme', 'Servis ödəmə məlumatlarını yeniləyə bilər'), ('delete_servisodeme', 'Servis ödəmə silə bilər'))},
        ),
    ]
