# Generated by Django 4.0.7 on 2022-12-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_alter_contract_compensation_expense_and_more'),
        ('services', '0002_remove_service_installment_service_pay_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='service',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='loan_term',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_amount_to_be_paid',
            field=models.FloatField(default=0),
        ),
    ]
