# Generated by Django 3.2.12 on 2022-09-07 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.holding')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_holdinggunler', 'Mövcud holdinq tətil günlərinə baxa bilər'), ('add_holdinggunler', 'Holdinqə tətil günü əlavə edə bilər'), ('change_holdinggunler', 'Holdinqin tətil günü məlumatlarını yeniləyə bilər'), ('delete_holdinggunler', 'Holdinqin tətil gününü silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='KomandaGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('komanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.komanda')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_komandagunler', 'Mövcud komanda tətil günlərinə baxa bilər'), ('add_komandagunler', 'Komanda tətil günü əlavə edə bilər'), ('change_komandagunler', 'Komandanın tətil günü məlumatlarını yeniləyə bilər'), ('delete_komandagunler', 'Komandanın tətil gününü silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OfisGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.ofis')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_ofisgunler', 'Mövcud ofis tətil günlərinə baxa bilər'), ('add_ofisgunler', 'Ofis tətil günü əlavə edə bilər'), ('change_ofisgunler', 'Ofisin tətil günü məlumatlarını yeniləyə bilər'), ('delete_ofisgunler', 'Ofisin tətil gününü silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ShirketGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.shirket')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_shirketgunler', 'Mövcud şirkət tətil günlərinə baxa bilər'), ('add_shirketgunler', 'Şirkət tətil günü əlavə edə bilər'), ('change_shirketgunler', 'Şirkətin tətil günü məlumatlarını yeniləyə bilər'), ('delete_shirketgunler', 'Şirkətin tətil gününü silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ShobeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('shobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.shobe')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_shobegunler', 'Mövcud şöbə tətil günlərinə baxa bilər'), ('add_shobegunler', 'Şöbə tətil günü əlavə edə bilər'), ('change_shobegunler', 'Şöbənin tətil günü məlumatlarını yeniləyə bilər'), ('delete_shobegunler', 'Şöbənin tətil gününü silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='VezifeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('vezife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_vezifegunler', 'Mövcud vəzifə tətil günlərinə baxa bilər'), ('add_vezifegunler', 'Vəzifə tətil günü əlavə edə bilər'), ('change_vezifegunler', 'Vəzifənin tətil günü məlumatlarını yeniləyə bilər'), ('delete_vezifegunler', 'Vəzifənin tətil gününü silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='VezifeIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.vezifegunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_vezifeistisnaisci', 'Mövcud vəzifə istisna işçilərə baxa bilər'), ('add_vezifeistisnaisci', 'Vəzifə istisna işçi əlavə edə bilər'), ('change_vezifeistisnaisci', 'Vəzifə istisna işçi məlumatlarını yeniləyə bilər'), ('delete_vezifeistisnaisci', 'Vəzifə istisna işçiməlumatalrını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ShobeIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.shobegunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_shobeistisnaisci', 'Mövcud şöbə istisna işçilərə baxa bilər'), ('add_shobeistisnaisci', 'Şöbə istisna işçi əlavə edə bilər'), ('change_shobeistisnaisci', 'Şöbə istisna işçi məlumatlarını yeniləyə bilər'), ('delete_shobeistisnaisci', 'Şöbə istisna işçiməlumatalrını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ShirketIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.shirketgunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_shirketistisnaisci', 'Mövcud şirkət istisna işçilərə baxa bilər'), ('add_shirketistisnaisci', 'Şirkət istisna işçi əlavə edə bilər'), ('change_shirketistisnaisci', 'Şirkət istisna işçi məlumatlarını yeniləyə bilər'), ('delete_shirketistisnaisci', 'Şirkət istisna işçiməlumatalrını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OfisIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.ofisgunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_ofisistisnaisci', 'Mövcud ofis istisna işçilərə baxa bilər'), ('add_ofisistisnaisci', 'Ofis istisna işçi əlavə edə bilər'), ('change_ofisistisnaisci', 'Ofis istisna işçi məlumatlarını yeniləyə bilər'), ('delete_ofisistisnaisci', 'Ofis istisna işçiməlumatalrını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='KomandaIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.komandagunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_komandaistisnaisci', 'Mövcud komanda istisna işçilərə baxa bilər'), ('add_komandaistisnaisci', 'Komanda istisna işçi əlavə edə bilər'), ('change_komandaistisnaisci', 'Komanda istisna işçi məlumatlarını yeniləyə bilər'), ('delete_komandaistisnaisci', 'Komanda istisna işçiməlumatalrını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='IsciGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('icaze_gunleri_odenisli', models.CharField(blank=True, max_length=500, null=True)),
                ('icaze_gunleri_odenissiz', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_odenisli', models.BooleanField(default=False)),
                ('odenis_meblegi', models.FloatField(blank=True, default=0)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_iscigunler', 'Mövcud işçilərin tətil günlərinə baxa bilər'), ('add_iscigunler', 'İşçilərə tətil günü əlavə edə bilər'), ('change_iscigunler', 'İşçilərin tətil günü məlumatlarını yeniləyə bilər'), ('delete_iscigunler', 'İşçilərin tətil gününü silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='IsciGelibGetmeVaxtlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelme_vaxti', models.TimeField()),
                ('getme_vaxti', models.TimeField()),
                ('isci', models.ManyToManyField(related_name='isci_gelib_getme_vaxtlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_iscigelibgetmevaxtlari', 'Mövcud işçi gəlib-getmə vaxtlarına baxa bilər'), ('add_iscigelibgetmevaxtlari', 'İşçi gəlib-getmə vaxtı əlavə edə bilər'), ('change_iscigelibgetmevaxtlari', 'İşçi gəlib-getmə vaxtının məlumatlarını yeniləyə bilər'), ('delete_iscigelibgetmevaxtlari', 'İşçi gəlib-getmə vaxtını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.holdinggunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_holdingistisnaisci', 'Mövcud holdinq istisna işçilərə baxa bilər'), ('add_holdingistisnaisci', 'Holdinq istisna işçi əlavə edə bilər'), ('change_holdingistisnaisci', 'Holdinq istisna işçi məlumatlarını yeniləyə bilər'), ('delete_holdingistisnaisci', 'Holdinq istisna işçiməlumatalrını silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
