# Generated by Django 3.2.12 on 2022-07-29 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.holding')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='KomandaGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('komanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.komanda')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.ofis')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.shirket')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShobeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('shobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.shobe')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='VezifeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('vezife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='VezifeIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.vezifegunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShobeIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.shobegunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.shirketgunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.ofisgunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='KomandaIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.komandagunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='IsciGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('icaze_gunleri_odenisli', models.CharField(blank=True, max_length=500, null=True)),
                ('icaze_gunleri_odenissiz', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_odenisli', models.BooleanField(default=False)),
                ('odenis_meblegi', models.FloatField(blank=True, default=0)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='IsciGelibGetmeVaxtlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelme_vaxti', models.TimeField()),
                ('getme_vaxti', models.TimeField()),
                ('isci', models.ManyToManyField(related_name='isci_gelib_getme_vaxtlari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='holiday.holdinggunler')),
                ('istisna_isciler', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
