# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdinggunler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_holdinggunler', 'Mövcud holdinq tətil günlərinə baxa bilər'), ('add_holdinggunler', 'Holdinqə tətil günü əlavə edə bilər'), ('change_holdinggunler', 'Holdinqin tətil günü məlumatlarını yeniləyə bilər'), ('delete_holdinggunler', 'Holdinqin tətil gününü silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='holdingistisnaisci',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_holdingistisnaisci', 'Mövcud holdinq istisna işçilərə baxa bilər'), ('add_holdingistisnaisci', 'Holdinq istisna işçi əlavə edə bilər'), ('change_holdingistisnaisci', 'Holdinq istisna işçi məlumatlarını yeniləyə bilər'), ('delete_holdingistisnaisci', 'Holdinq istisna işçiməlumatalrını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='iscigelibgetmevaxtlari',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_iscigelibgetmevaxtlari', 'Mövcud işçi gəlib-getmə vaxtlarına baxa bilər'), ('add_iscigelibgetmevaxtlari', 'İşçi gəlib-getmə vaxtı əlavə edə bilər'), ('change_iscigelibgetmevaxtlari', 'İşçi gəlib-getmə vaxtının məlumatlarını yeniləyə bilər'), ('delete_iscigelibgetmevaxtlari', 'İşçi gəlib-getmə vaxtını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='iscigunler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_iscigunler', 'Mövcud işçilərin tətil günlərinə baxa bilər'), ('add_iscigunler', 'İşçilərə tətil günü əlavə edə bilər'), ('change_iscigunler', 'İşçilərin tətil günü məlumatlarını yeniləyə bilər'), ('delete_iscigunler', 'İşçilərin tətil gününü silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='komandagunler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_komandagunler', 'Mövcud komanda tətil günlərinə baxa bilər'), ('add_komandagunler', 'Komanda tətil günü əlavə edə bilər'), ('change_komandagunler', 'Komandanın tətil günü məlumatlarını yeniləyə bilər'), ('delete_komandagunler', 'Komandanın tətil gününü silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='komandaistisnaisci',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_komandaistisnaisci', 'Mövcud komanda istisna işçilərə baxa bilər'), ('add_komandaistisnaisci', 'Komanda istisna işçi əlavə edə bilər'), ('change_komandaistisnaisci', 'Komanda istisna işçi məlumatlarını yeniləyə bilər'), ('delete_komandaistisnaisci', 'Komanda istisna işçiməlumatalrını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='ofisgunler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_ofisgunler', 'Mövcud ofis tətil günlərinə baxa bilər'), ('add_ofisgunler', 'Ofis tətil günü əlavə edə bilər'), ('change_ofisgunler', 'Ofisin tətil günü məlumatlarını yeniləyə bilər'), ('delete_ofisgunler', 'Ofisin tətil gününü silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='ofisistisnaisci',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_ofisistisnaisci', 'Mövcud ofis istisna işçilərə baxa bilər'), ('add_ofisistisnaisci', 'Ofis istisna işçi əlavə edə bilər'), ('change_ofisistisnaisci', 'Ofis istisna işçi məlumatlarını yeniləyə bilər'), ('delete_ofisistisnaisci', 'Ofis istisna işçiməlumatalrını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirketgunler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_shirketgunler', 'Mövcud şirkət tətil günlərinə baxa bilər'), ('add_shirketgunler', 'Şirkət tətil günü əlavə edə bilər'), ('change_shirketgunler', 'Şirkətin tətil günü məlumatlarını yeniləyə bilər'), ('delete_shirketgunler', 'Şirkətin tətil gününü silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirketistisnaisci',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_shirketistisnaisci', 'Mövcud şirkət istisna işçilərə baxa bilər'), ('add_shirketistisnaisci', 'Şirkət istisna işçi əlavə edə bilər'), ('change_shirketistisnaisci', 'Şirkət istisna işçi məlumatlarını yeniləyə bilər'), ('delete_shirketistisnaisci', 'Şirkət istisna işçiməlumatalrını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shobegunler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_shobegunler', 'Mövcud şöbə tətil günlərinə baxa bilər'), ('add_shobegunler', 'Şöbə tətil günü əlavə edə bilər'), ('change_shobegunler', 'Şöbənin tətil günü məlumatlarını yeniləyə bilər'), ('delete_shobegunler', 'Şöbənin tətil gününü silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shobeistisnaisci',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_shobeistisnaisci', 'Mövcud şöbə istisna işçilərə baxa bilər'), ('add_shobeistisnaisci', 'Şöbə istisna işçi əlavə edə bilər'), ('change_shobeistisnaisci', 'Şöbə istisna işçi məlumatlarını yeniləyə bilər'), ('delete_shobeistisnaisci', 'Şöbə istisna işçiməlumatalrını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='vezifegunler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_vezifegunler', 'Mövcud vəzifə tətil günlərinə baxa bilər'), ('add_vezifegunler', 'Vəzifə tətil günü əlavə edə bilər'), ('change_vezifegunler', 'Vəzifənin tətil günü məlumatlarını yeniləyə bilər'), ('delete_vezifegunler', 'Vəzifənin tətil gününü silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='vezifeistisnaisci',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_vezifeistisnaisci', 'Mövcud vəzifə istisna işçilərə baxa bilər'), ('add_vezifeistisnaisci', 'Vəzifə istisna işçi əlavə edə bilər'), ('change_vezifeistisnaisci', 'Vəzifə istisna işçi məlumatlarını yeniləyə bilər'), ('delete_vezifeistisnaisci', 'Vəzifə istisna işçiməlumatalrını silə bilər'))},
        ),
    ]
