# Generated by Django 4.0.7 on 2022-11-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0006_employeedayoffhistory_employeedayoffoperation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedayoffoperation',
            old_name='holiday_date',
            new_name='day_off_date',
        ),
    ]
