# Generated by Django 3.2.12 on 2022-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAndRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateField(blank=True, null=True)),
                ('restore_date', models.DateField(blank=True, null=True)),
                ('media_backup_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
