# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_restore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupandrestore',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_backupandrestore', 'Mövcud `backup and restore`lara baxa bilər'), ('add_backupandrestore', '`Backup and restore` əlavə edə bilər'), ('change_backupandrestore', '`Backup and restore` məlumatlarını yeniləyə bilər'), ('delete_backupandrestore', '`Backup and restore` silə bilər'))},
        ),
    ]
