KREDIT = 'KREDİT'
NAGD = 'NƏĞD'

ODENIS_USLUBU_CHOICES = [
    (NAGD, "NƏĞD"),
    (KREDIT, "KREDİT"),
]

BITMIS = "BİTMİŞ"
DAVAM_EDEN = "DAVAM EDƏN"
DUSEN = "DÜŞƏN"
YOXDUR = "YOXDUR"
YENI_QRAFIK = "YENİ QRAFİK"

YENI_QRAFIK_CHOICES = [
    (YENI_QRAFIK, "YENİ QRAFİK")
]

MUQAVILE_STATUS_CHOICES = [
    (DAVAM_EDEN, "DAVAM EDƏN"),
    (BITMIS, "BİTMİŞ"),
    (DUSEN, "DÜŞƏN")
]

ILKIN_ODENIS_STATUS_CHOICES = [
    (YOXDUR, "YOXDUR"),
    (BITMIS, "BİTMİŞ"),
    (DAVAM_EDEN, "DAVAM EDƏN"),
]

QALIQ_ILKIN_ODENIS_STATUS_CHOICES = [
    (YOXDUR, "YOXDUR"),
    (BITMIS, "BİTMİŞ"),
    (DAVAM_EDEN, "DAVAM EDƏN"),
]

NAGD_ODENIS_1_STATUS_CHOICES = [
    (YOXDUR, "YOXDUR"),
    (BITMIS, "BİTMİŞ"),
    (DAVAM_EDEN, "DAVAM EDƏN"),
]

NAGD_ODENIS_2_STATUS_CHOICES = [
    (YOXDUR, "YOXDUR"),
    (BITMIS, "BİTMİŞ"),
    (DAVAM_EDEN, "DAVAM EDƏN"),
]

DEYISMIS_MEHSUL = "DƏYİŞİLMİŞ MƏHSUL"

DEYISMIS_MEHSUL_STATUS_CHOICES = [
    (DEYISMIS_MEHSUL, "DƏYİŞİLMİŞ MƏHSUL")
]

ODENEN = "ÖDƏNƏN"
ODENMEYEN = "ÖDƏNMƏYƏN"

BURAXILMIS_AY = "BURAXILMIŞ AY"
NATAMAM_AY = "NATAMAM AY"
RAZILASDIRILMIS_AZ_ODEME = "RAZILAŞDIRILMIŞ AZ ÖDƏMƏ"
ARTIQ_ODEME = "ARTIQ ÖDƏMƏ"
SON_AYIN_BOLUNMESI = "SON AYIN BÖLÜNMƏSİ"

GECIKDIRME = "GECİKDİRMƏ"

SIFIR_NOVBETI_AY = "SIFIR NÖVBƏTİ AY"
SIFIR_SONUNCU_AY = "SIFIR SONUNCU AY"
SIFIR_DIGER_AYLAR = "SIFIR DİGƏR AYLAR"

NATAMAM_NOVBETI_AY = "NATAMAM NÖVBƏTİ AY"
NATAMAM_SONUNCU_AY = "NATAMAM SONUNCU AY"
NATAMAM_DIGER_AYLAR = "NATAMAM DİGƏR AYLAR"

ARTIQ_BIR_AY = "ARTIQ BİR AY"
ARTIQ_BUTUN_AYLAR = "ARTIQ BÜTÜN AYLAR"

BORCU_BAGLA = "BORCU BAĞLA"

ODEME_STATUS_CHOICES = [
    (ODENMEYEN, "ÖDƏNMƏYƏN"),
    (ODENEN, "ÖDƏNƏN"),
]

SERTLI_ODEME_STATUSU = [
    (BURAXILMIS_AY, "BURAXILMIŞ AY"),
    (NATAMAM_AY, "NATAMAM AY"),
    (RAZILASDIRILMIS_AZ_ODEME, "RAZILAŞDIRILMIŞ AZ ÖDƏMƏ"),
    (ARTIQ_ODEME, "ARTIQ ÖDƏMƏ"),
    (SON_AYIN_BOLUNMESI, "SON AYIN BÖLÜNMƏSİ")
]

GECIKDIRME_STATUS_CHOICES = [
    (GECIKDIRME, "GECİKDİRMƏ")
]

SIFIR_STATUS_CHOICES = [
    (SIFIR_NOVBETI_AY, "SIFIR NÖVBƏTİ AY"),
    (SIFIR_SONUNCU_AY, "SIFIR SONUNCU AY"),
    (SIFIR_DIGER_AYLAR, "SIFIR DİGƏR AYLAR")
]

NATAMAM_STATUS_CHOICES = [
    (NATAMAM_NOVBETI_AY, "NATAMAM NÖVBƏTİ AY"),
    (NATAMAM_SONUNCU_AY, "NATAMAM SONUNCU AY"),
    (NATAMAM_DIGER_AYLAR, "NATAMAM DİGƏR AYLAR")
]

ARTIQ_ODEME_STATUS_CHOICES = [
    (ARTIQ_BIR_AY, "ARTIQ BİR AY"),
    (ARTIQ_BUTUN_AYLAR, "ARTIQ BÜTÜN AYLAR")
]

BORCU_BAGLA_STATUS_CHOICES = [
    (BORCU_BAGLA, "BORCU BAĞLA")
]
