# Generated by Django 4.0.7 on 2022-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_unique product name for your constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='guarantee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
