# Generated by Django 4.0.7 on 2022-12-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_quantity_alter_product_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
