# Generated by Django 3.2.9 on 2023-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_category', 'Mövcud kateqoriyalara baxa bilər'), ('add_category', 'Kateqoriya əlavə edə bilər'), ('change_category', 'Kateqoriya məlumatlarını yeniləyə bilər'), ('delete_category', 'Kateqoriya silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_product', 'Mövcud məhsullara baxa bilər'), ('add_product', 'Məhsul əlavə edə bilər'), ('change_product', 'Məhsul məlumatlarını yeniləyə bilər'), ('delete_product', 'Məhsul silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_unitofmeasure', 'Mövcud ölçü vahidlərinə baxa bilər'), ('add_unitofmeasure', 'Ölçü vahidi əlavə edə bilər'), ('change_unitofmeasure', 'Ölçü vahidi məlumatlarını yeniləyə bilər'), ('delete_unitofmeasure', 'Ölçü vahidini silə bilər'))},
        ),
    ]
