# Generated by Django 4.0.7 on 2022-12-10 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_remove_section_office'),
        ('product', '0008_remove_product_quantity_alter_product_guarantee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeUnuselessOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_and_quantity', models.CharField(max_length=500)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_changeunuselessoperation', 'Mövcud utilizasiyalara baxa bilər'), ('add_changeunuselessoperation', 'Utilizasiya edə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company.company')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company.office')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_warehouse', 'Mövcud anbarlara baxa bilər'), ('add_warehouse', 'Anbar əlavə edə bilər'), ('change_warehouse', 'Anbar məlumatlarını yeniləyə bilər'), ('delete_warehouse', 'Anbar silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_and_quantity', models.CharField(blank=True, max_length=250, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('employee_who_sent_the_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_note', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_warehouserequest', 'Mövcud anbar sorğularına baxa bilər'), ('add_warehouserequest', 'Anbar sorğu əlavə edə bilər'), ('change_warehouserequest', 'Anbar sorğu məlumatlarını yeniləyə bilər'), ('delete_warehouserequest', 'Anbar sorğu silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('useful_product_count', models.PositiveIntegerField(default=0)),
                ('changed_product_count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_stock', 'Mövcud stoklara baxa bilər'), ('add_stock', 'Stock əlavə edə bilər'), ('change_stock', 'Stock məlumatlarını yeniləyə bilər'), ('delete_stock', 'Stock silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_and_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('operation_date', models.DateField(auto_now_add=True, null=True)),
                ('operation_type', models.CharField(choices=[('transfer', 'transfer'), ('stock yeniləmə', 'stock yeniləmə')], default='transfer', max_length=50)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation', to=settings.AUTH_USER_MODEL)),
                ('receiving_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_warehouse', to='warehouse.warehouse')),
                ('shipping_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_operation', 'Mövcud əməliyyatlara baxa bilər'), ('add_operation', 'Əməliyyat əlavə edə bilər'), ('change_operation', 'Əməliyyat məlumatlarını yeniləyə bilər'), ('delete_operation', 'Əməliyyat silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('useful_product_count', models.PositiveIntegerField(default=0)),
                ('unuseful_product_count', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_warehouse', to='product.product')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_holdingwarehouse', 'Holding anbarına baxa bilər'),),
                'default_permissions': [],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('name', 'office'), name='unique name for your warehouse constraint'),
        ),
    ]
