# Generated by Django 4.0.7 on 2022-12-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_section_office'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingwarehouse',
            name='holding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holding_warehouse', to='company.holding'),
            preserve_default=False,
        ),
    ]
