# Generated by Django 4.0.7 on 2022-12-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_holdingwarehouse_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingwarehouse',
            name='holding',
        ),
    ]
