# Generated by Django 4.0.7 on 2022-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_holdingwarehouse_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='is_done',
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='status',
            field=models.CharField(choices=[('Yerinə Yetirilib', 'Yerinə Yetirilib'), ('Yerinə Yetirilməyib', 'Yerinə Yetirilməyib'), ('İmtina edildi', 'İmtina edildi')], default='Yerinə Yetirilməyib', max_length=100),
        ),
    ]
