# Generated by Django 4.0.7 on 2022-12-12 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_remove_section_office'),
        ('account', '0015_alter_user_salary'),
        ('warehouse', '0004_remove_operation_operation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sender_warehouse', models.CharField(blank=True, max_length=250, null=True)),
                ('receiving_warehouse', models.CharField(blank=True, max_length=250, null=True)),
                ('sender_previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sender_subsequent_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recepient_previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recepient_subsequent_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('products_and_quantity', models.CharField(blank=True, max_length=800, null=True)),
                ('operation_style', models.CharField(blank=True, choices=[('Transfer', 'Transfer'), ('Giriş', 'Giriş'), ('Utilizasiya', 'Utilizasiya'), ('Yeniləmə', 'Yeniləmə'), ('Servis', 'Servis'), ('Söküntü', 'Söküntü'), ('Dəyişim', 'Dəyişim'), ('Satış', 'Satış')], max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_histories', to='company.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_histories', to='account.customer')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_warehousehistory', 'Mövcud utilizasiyalara baxa bilər'),),
                'default_permissions': [],
            },
        ),
        migrations.AlterField(
            model_name='changeunuselessoperation',
            name='products_and_quantity',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='product_and_quantity',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
