# Generated by Django 4.0.7 on 2022-12-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_warehousehistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousehistory',
            name='recepient_previous_balance',
        ),
        migrations.RemoveField(
            model_name='warehousehistory',
            name='recepient_subsequent_balance',
        ),
        migrations.RemoveField(
            model_name='warehousehistory',
            name='sender_previous_balance',
        ),
        migrations.RemoveField(
            model_name='warehousehistory',
            name='sender_subsequent_balance',
        ),
        migrations.AddField(
            model_name='warehousehistory',
            name='recepient_previous_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousehistory',
            name='recepient_subsequent_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousehistory',
            name='sender_previous_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousehistory',
            name='sender_subsequent_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
