# Generated by Django 4.0.7 on 2022-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_remove_warehousehistory_recepient_previous_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousehistory',
            name='products_and_quantity',
        ),
        migrations.AddField(
            model_name='warehousehistory',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warehousehistory',
            name='product_quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
