# Generated by Django 4.0.7 on 2022-12-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_warehousehistory_products_and_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousehistory',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
