# Generated by Django 3.2.9 on 2023-02-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20230203_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingwarehouse',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_holdingwarehouse', 'Holding anbarına baxa bilər'), ('add_holdingwarehouse', 'Holding anbar əlavə edə bilər'), ('change_holdingwarehouse', 'Holding anbar məlumatlarını yeniləyə bilər'), ('delete_holdingwarehouse', 'Holding anbar silə bilər'))},
        ),
    ]
