# Generated by Django 3.2.9 on 2023-02-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_holdingwarehouse_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousehistory',
            name='operation_style',
            field=models.CharField(blank=True, choices=[('Transfer', 'Transfer'), ('Giriş', 'Giriş'), ('Utilizasiya', 'Utilizasiya'), ('Yeniləmə', 'Yeniləmə'), ('Servis', 'Servis'), ('Söküntü', 'Söküntü'), ('Dəyişim', 'Dəyişim'), ('Satış', 'Satış'), ('Hədiyyə', 'Hədiyyə')], max_length=150, null=True),
        ),
    ]
