# Generated by Django 3.2.12 on 2022-09-07 10:36

import core.image_validator
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logo/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
            ],
            options={
                'permissions': (('view_logo', 'Logoya baxa bilər'), ('add_logo', 'Logo əlavə edə bilər'), ('change_logo', 'Logonu yeniləyə bilər'), ('delete_logo', 'Logonu silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_adi', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_holding', 'Mövcud holdinqlərə baxa bilər'), ('add_holding', 'Holdinq əlavə edə bilər'), ('change_holding', 'Holdinq məlumatlarını yeniləyə bilər'), ('delete_holding', 'Holdinq silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Komanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komanda_adi', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_komanda', 'Mövcud komandalara baxa bilər'), ('add_komanda', 'Komanda əlavə edə bilər'), ('change_komanda', 'Komanda məlumatlarını yeniləyə bilər'), ('delete_komanda', 'Komanda silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Ofis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofis_adi', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_ofis', 'Mövcud ofislərə baxa bilər'), ('add_ofis', 'Ofis əlavə edə bilər'), ('change_ofis', 'Ofis məlumatlarını yeniləyə bilər'), ('delete_ofis', 'Ofis silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Shirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirket_adi', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_shirket', to='company.holding')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_shirket', 'Mövcud şirkətlərə baxa bilər'), ('add_shirket', 'Şirkət əlavə edə bilər'), ('change_shirket', 'Şirkət məlumatlarını yeniləyə bilər'), ('delete_shirket', 'Şirkət silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Shobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shobe_adi', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe', to='company.ofis')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_shobe', 'Mövcud şöbələrə baxa bilər'), ('add_shobe', 'Şöbə əlavə edə bilər'), ('change_shobe', 'Şöbə məlumatlarını yeniləyə bilər'), ('delete_shobe', 'Şöbə silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vezifeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezife_adi', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_vezifeleri', to='company.shirket')),
                ('shobe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe_vezife', to='company.shobe')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_vezifeler', 'Mövcud vəzifələrə baxa bilər'), ('add_vezifeler', 'Vəzifə əlavə edə bilər'), ('change_vezifeler', 'Vəzifə məlumatlarını yeniləyə bilər'), ('delete_vezifeler', 'Vəzifə silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='VezifePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vezife_permission', to='auth.group')),
                ('vezife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vezife_permission', to='company.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_vezifepermission', 'Mövcud Vəzifə icazələrinə baxa bilər'), ('add_vezifepermission', 'Vəzifə icazə əlavə edə bilər'), ('change_vezifepermission', 'Vəzifə icazə məlumatlarını yeniləyə bilər'), ('delete_vezifepermission', 'Vəzifə icazə məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='ofis',
            name='shirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_ofis', to='company.shirket'),
        ),
    ]
