# Generated by Django 3.2.12 on 2022-07-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VezifePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vezife_permission', to='auth.group')),
                ('vezife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vezife_permission', to='company.vezifeler')),
            ],
        ),
    ]
