# Generated by Django 3.2.12 on 2022-09-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220917_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_department', 'Mövcud departamentlərə baxa bilər'), ('add_department', 'Departament əlavə edə bilər'), ('change_department', 'Departament məlumatlarını yeniləyə bilər'), ('delete_department', 'Departament silə bilər'))},
        ),
    ]
