# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_vezifepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_holding', 'Mövcud holdinqlərə baxa bilər'), ('add_holding', 'Holdinq əlavə edə bilər'), ('change_holding', 'Holdinq məlumatlarını yeniləyə bilər'), ('delete_holding', 'Holdinq silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='komanda',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_komanda', 'Mövcud komandalara baxa bilər'), ('add_komanda', 'Komanda əlavə edə bilər'), ('change_komanda', 'Komanda məlumatlarını yeniləyə bilər'), ('delete_komanda', 'Komanda silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='ofis',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_ofis', 'Mövcud ofislərə baxa bilər'), ('add_ofis', 'Ofis əlavə edə bilər'), ('change_ofis', 'Ofis məlumatlarını yeniləyə bilər'), ('delete_ofis', 'Ofis silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirket',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_shirket', 'Mövcud şirkətlərə baxa bilər'), ('add_shirket', 'Şirkət əlavə edə bilər'), ('change_shirket', 'Şirkət məlumatlarını yeniləyə bilər'), ('delete_shirket', 'Şirkət silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shobe',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_shobe', 'Mövcud şöbələrə baxa bilər'), ('add_shobe', 'Şöbə əlavə edə bilər'), ('change_shobe', 'Şöbə məlumatlarını yeniləyə bilər'), ('delete_shobe', 'Şöbə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='vezifeler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_vezifeler', 'Mövcud vəzifələrə baxa bilər'), ('add_vezifeler', 'Vəzifə əlavə edə bilər'), ('change_vezifeler', 'Vəzifə məlumatlarını yeniləyə bilər'), ('delete_vezifeler', 'Vəzifə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='vezifepermission',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_vezifepermission', 'Mövcud Vəzifə icazələrinə baxa bilər'), ('add_vezifepermission', 'Vəzifə icazə əlavə edə bilər'), ('change_vezifepermission', 'Vəzifə icazə məlumatlarını yeniləyə bilər'), ('delete_vezifepermission', 'Vəzifə icazə məlumatlarını silə bilər'))},
        ),
    ]
