# Generated by Django 4.0.7 on 2022-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_department_company_department_holding'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique name for your office constraint'),
        ),
    ]
