# Generated by Django 3.2.12 on 2022-08-16 12:27

import core.image_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220811_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
            ],
            options={
                'permissions': (('view_logo', 'Logoya baxa bilər'), ('add_logo', 'Logo əlavə edə bilər'), ('change_logo', 'Logonu yeniləyə bilər'), ('delete_logo', 'Logonu silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
