# Generated by Django 3.2.12 on 2022-08-16 13:30

import core.image_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_applogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
