# Generated by Django 4.0.7 on 2022-10-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_holding_alter_company_web_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='holding',
        ),
        migrations.RemoveField(
            model_name='department',
            name='holding',
        ),
    ]
