# Generated by Django 4.0.7 on 2022-11-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_position_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='office',
        ),
    ]
