# Generated by Django 3.2.9 on 2023-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_section_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_company', 'Mövcud şirkətlərə baxa bilər'), ('add_company', 'Şirkət əlavə edə bilər'), ('change_company', 'Şirkət məlumatlarını yeniləyə bilər'), ('delete_company', 'Şirkət silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_department', 'Mövcud departamentlərə baxa bilər'), ('add_department', 'Departament əlavə edə bilər'), ('change_department', 'Departament məlumatlarını yeniləyə bilər'), ('delete_department', 'Departament silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_holding', 'Mövcud holdinqlərə baxa bilər'), ('add_holding', 'Holdinq əlavə edə bilər'), ('change_holding', 'Holdinq məlumatlarını yeniləyə bilər'), ('delete_holding', 'Holdinq silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_office', 'Mövcud ofislərə baxa bilər'), ('add_office', 'Ofis əlavə edə bilər'), ('change_office', 'Ofis məlumatlarını yeniləyə bilər'), ('delete_office', 'Ofis silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='permissionforposition',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_permissionforposition', 'Mövcud Vəzifə icazələrinə baxa bilər'), ('add_permissionforposition', 'Vəzifə icazə əlavə edə bilər'), ('change_permissionforposition', 'Vəzifə icazə məlumatlarını yeniləyə bilər'), ('delete_permissionforposition', 'Vəzifə icazə məlumatlarını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_position', 'Mövcud vəzifələrə baxa bilər'), ('add_position', 'Vəzifə əlavə edə bilər'), ('change_position', 'Vəzifə məlumatlarını yeniləyə bilər'), ('delete_position', 'Vəzifə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_section', 'Mövcud şöbələrə baxa bilər'), ('add_section', 'Şöbə əlavə edə bilər'), ('change_section', 'Şöbə məlumatlarını yeniləyə bilər'), ('delete_section', 'Şöbə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_team', 'Mövcud komandalara baxa bilər'), ('add_team', 'Komanda əlavə edə bilər'), ('change_team', 'Komanda məlumatlarını yeniləyə bilər'), ('delete_team', 'Komanda silə bilər'))},
        ),
    ]
