# Generated by Django 3.2.12 on 2022-09-07 10:36

import core.image_validator
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('asa', models.CharField(max_length=200)),
                ('dogum_tarixi', models.DateField(blank=True, null=True)),
                ('ishe_baslama_tarixi', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ishden_cixma_tarixi', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('tel1', models.CharField(max_length=200)),
                ('tel2', models.CharField(blank=True, max_length=200, null=True)),
                ('sv_image', models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('sv_image2', models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('elektron_imza', models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('maas_uslubu', models.CharField(choices=[('PRİM', 'PRİM'), ('FİX', 'FİX'), ('FİX+PRİM', 'FİX+PRİM')], default='FİX', max_length=50)),
                ('maas', models.FloatField(blank=True, default=0, null=True)),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/profile/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_user', 'Mövcud işçilərə baxa bilər'), ('add_user', 'İşçi əlavə edə bilər'), ('change_user', 'İşçi məlumatlarını yeniləyə bilər'), ('delete_user', 'İşçi silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Bolge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolge_adi', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_bolge', 'Mövcud bölgələrə baxa bilər'), ('add_bolge', 'Bölgə əlavə edə bilər'), ('change_bolge', 'Bölgə məlumatlarını yeniləyə bilər'), ('delete_bolge', 'Bölgə silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='IsciStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_adi', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_iscistatus', 'Mövcud işçi statuslarına baxa bilər'), ('add_iscistatus', 'İşçi statusu əlavə edə bilər'), ('change_iscistatus', 'İşçi statusu məlumatlarını yeniləyə bilər'), ('delete_iscistatus', 'İşçi statusunu silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asa', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('sv_image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('sv_image2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('tel1', models.CharField(max_length=50)),
                ('tel2', models.CharField(blank=True, max_length=50, null=True)),
                ('tel3', models.CharField(blank=True, max_length=50, null=True)),
                ('tel4', models.CharField(blank=True, max_length=50, null=True)),
                ('unvan', models.TextField(blank=True)),
                ('qeyd', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('bolge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bolge')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_musteri', 'Mövcud müştərilərə baxa bilər'), ('add_musteri', 'Müştəri əlavə edə bilər'), ('change_musteri', 'Müştəri məlumatlarını yeniləyə bilər'), ('delete_musteri', 'Müştəri silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='MusteriQeydler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qeyd', models.TextField()),
                ('tarix', models.DateField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musteri_qeydler', to='account.musteri')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_musteriqeydler', 'Mövcud müştəri qeydlərinə baxa bilər'), ('add_musteriqeydler', 'Müştəri qeydi əlavə edə bilər'), ('change_musteriqeydler', 'Müştəri qeydinin məlumatlarını yeniləyə bilər'), ('delete_musteriqeydler', 'Müştəri qeydlərini silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='IsciSatisSayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarix', models.DateField()),
                ('satis_sayi', models.PositiveIntegerField(default=0, null=True)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_satis_sayi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_iscisatissayi', 'Mövcud işçi satış saylarına baxa bilər'), ('add_iscisatissayi', 'İşçi satış sayı əlavə edə bilər'), ('change_iscisatissayi', 'İşçi satış sayı məlumatlarını yeniləyə bilər'), ('delete_iscisatissayi', 'İşçi satış sayı silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='isci_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus'),
        ),
        migrations.AddField(
            model_name='user',
            name='komanda',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_komanda', to='company.komanda'),
        ),
        migrations.AddField(
            model_name='user',
            name='ofis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.ofis'),
        ),
        migrations.AddField(
            model_name='user',
            name='shirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shirket'),
        ),
        migrations.AddField(
            model_name='user',
            name='shobe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shobe'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='vezife',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vezife', to='company.vezifeler'),
        ),
    ]
