# Generated by Django 3.2.12 on 2022-09-09 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='elektron_imza',
            new_name='suruculuk_vesiqesi',
        ),
        migrations.AddField(
            model_name='user',
            name='muqavile_novu',
            field=models.CharField(blank=True, choices=[('xidməti müqavilə', 'xidməti müqavilə'), ('əmək müqaviləsi', 'əmək müqaviləsi')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='maas_uslubu',
            field=models.CharField(choices=[('aylıq', 'aylıq'), ('günlük', 'günlük'), ('həftəlik', 'həftəlik')], default='aylıq', max_length=50),
        ),
    ]
