# Generated by Django 3.2.12 on 2022-08-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_musteri_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musteri',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_musteri', 'Mövcud müştərilərə baxa bilər '), ('add_musteri', 'Müştəri əlavə edə bilər'), ('change_musteri', 'Müştəri məlumatlarını yeniləyə bilər'), ('delete_musteri', 'Müştəri silə bilər'))},
        ),
    ]
