# Generated by Django 3.2.12 on 2022-09-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_department_options'),
        ('account', '0003_alter_user_maas_uslubu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.department'),
        ),
    ]
