# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_musteri_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iscisatissayi',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_iscisatissayi', 'Mövcud işçi satış saylarına baxa bilər'), ('add_iscisatissayi', 'İşçi satış sayı əlavə edə bilər'), ('change_iscisatissayi', 'İşçi satış sayı məlumatlarını yeniləyə bilər'), ('delete_iscisatissayi', 'İşçi satış sayı silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='iscistatus',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_iscistatus', 'Mövcud işçi statuslarına baxa bilər'), ('add_iscistatus', 'İşçi statusu əlavə edə bilər'), ('change_iscistatus', 'İşçi statusu məlumatlarını yeniləyə bilər'), ('delete_iscistatus', 'İşçi statusunu silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='musteri',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_musteri', 'Mövcud müştərilərə baxa bilər'), ('add_musteri', 'Müştəri əlavə edə bilər'), ('change_musteri', 'Müştəri məlumatlarını yeniləyə bilər'), ('delete_musteri', 'Müştəri silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='musteriqeydler',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_musteriqeydler', 'Mövcud müştəri qeydlərinə baxa bilər'), ('add_musteriqeydler', 'Müştəri qeydi əlavə edə bilər'), ('change_musteriqeydler', 'Müştəri qeydinin məlumatlarını yeniləyə bilər'), ('delete_musteriqeydler', 'Müştəri qeydlərini silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_user', 'Mövcud işçilərə baxa bilər'), ('add_user', 'İşçi əlavə edə bilər'), ('change_user', 'İşçi məlumatlarını yeniləyə bilər'), ('delete_user', 'İşçi silə bilər'))},
        ),
    ]
