# Generated by Django 4.0.7 on 2022-09-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dogum_tarixi',
        ),
    ]
