# Generated by Django 4.0.7 on 2022-09-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_department_options'),
        ('account', '0005_remove_user_dogum_tarixi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vezife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vezife', to='company.vezifeler'),
        ),
    ]
