# Generated by Django 4.0.7 on 2022-09-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_vezife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='qeyd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
