# Generated by Django 4.0.7 on 2022-11-22 07:11

import core.image_validator
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='holding',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='electronic_signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_type',
            field=models.CharField(choices=[('Holding', 'Holding'), ('Şirkət', 'Şirkət')], default='Şirkət', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_style',
            field=models.CharField(choices=[('aylıq', 'aylıq'), ('günlük', 'günlük'), ('həftəlik', 'həftəlik'), ('fix', 'fix')], default='aylıq', max_length=50),
        ),
    ]
