# Generated by Django 3.2.12 on 2022-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ishden_cixma_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ishe_baslama_tarixi',
            field=models.DateField(blank=True, default='19-08-2022', null=True),
        ),
    ]
