# Generated by Django 3.2.12 on 2022-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220819_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ishe_baslama_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
