# Generated by Django 4.0.7 on 2022-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muqavile',
            name='shobe',
        ),
        migrations.AddField(
            model_name='muqavile',
            name='qeyd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
