# Generated by Django 3.2.12 on 2022-08-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='muqavile_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
