# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20220804_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demosatis',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_demosatis', 'Mövcud demo satışlara baxa bilər'), ('add_demosatis', 'Demo satış əlavə edə bilər'), ('change_demosatis', 'Demo satış məlumatlarını yeniləyə bilər'), ('delete_demosatis', 'Demo satış silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='deyisim',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_deyisim', 'Mövcud dəyişimlərə baxa bilər'), ('add_deyisim', 'Dəyişim əlavə edə bilər'), ('change_deyisim', 'Dəyişim məlumatlarını yeniləyə bilər'), ('delete_deyisim', 'Dəyişim silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='muqavile',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_muqavile', 'Mövcud müqavilələrə baxa bilər'), ('add_muqavile', 'Müqavilə əlavə edə bilər'), ('change_muqavile', 'Müqavilə məlumatlarını yeniləyə bilər'), ('delete_muqavile', 'Müqavilə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='muqavilehediyye',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_muqavilehediyye', 'Mövcud müqavilə hədiyyələrə baxa bilər'), ('add_muqavilehediyye', 'Müqavilə hədiyyə əlavə edə bilər'), ('change_muqavilehediyye', 'Müqavilə hədiyyə məlumatlarını yeniləyə bilər'), ('delete_muqavilehediyye', 'Müqavilə hədiyyə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='muqavilekreditor',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_muqavilekreditor', 'Mövcud kreditorlara baxa bilər'), ('add_muqavilekreditor', 'Müqavilə Kreditor əlavə edə bilər'), ('change_muqavilekreditor', 'Müqavilə Kreditor məlumatlarını yeniləyə bilər'), ('delete_muqavilekreditor', 'Müqavilə Kreditor silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='odemetarix',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_odemetarix', 'Mövcud ödəmələrə baxa bilər'), ('add_odemetarix', 'Ödəmə əlavə edə bilər'), ('change_odemetarix', 'Ödəmə məlumatlarını yeniləyə bilər'), ('delete_odemetarix', 'Ödəmə silə bilər'))},
        ),
    ]
