# Generated by Django 3.2.12 on 2022-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20220811_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='borc_baglanma_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
