# Generated by Django 3.2.12 on 2022-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_muqavile_borc_baglanma_tarixi'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='borc_baglanma_statusu',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
