# Generated by Django 3.2.12 on 2022-08-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_muqavile_borc_baglanma_statusu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muqavile',
            name='borc_baglanma_statusu',
        ),
    ]
