# Generated by Django 4.0.7 on 2022-12-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_contract_compensation_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='initial_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
