# Generated by Django 3.2.12 on 2022-07-29 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('company', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KreditorPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prim_faizi', models.PositiveBigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VanLeaderPrimNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(blank=True, default=0, null=True)),
                ('negd', models.FloatField(blank=True, default=0)),
                ('kredit_4_12', models.FloatField(blank=True, default=0)),
                ('kredit_13_18', models.FloatField(blank=True, default=0)),
                ('kredit_19_24', models.FloatField(blank=True, default=0)),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VanLeaderPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(blank=True, default=0, null=True)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('komandaya_gore_prim', models.FloatField(blank=True, default=0)),
                ('fix_maas', models.FloatField(blank=True, default=0)),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeLeaderPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(blank=True, default=0, null=True)),
                ('ofise_gore_prim', models.FloatField(blank=True, default=0)),
                ('fix_maas', models.FloatField(blank=True, default=0)),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaasOde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('qeyd', models.TextField(blank=True, default='')),
                ('odeme_tarixi', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('isci', models.ManyToManyField(related_name='maas_ode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='MaasGoruntuleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_sayi', models.PositiveBigIntegerField(blank=True, default=0)),
                ('satis_meblegi', models.FloatField(blank=True, default=0)),
                ('yekun_maas', models.FloatField(blank=True, default=0)),
                ('tarix', models.DateField(blank=True, null=True)),
                ('odendi', models.BooleanField(default=False)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_maas_goruntuleme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Kesinti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('qeyd', models.TextField(blank=True, default='')),
                ('kesinti_tarixi', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_kesinti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='DealerPrimNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(blank=True, default=0, null=True)),
                ('negd', models.FloatField(blank=True, default=0)),
                ('kredit_4_12', models.FloatField(blank=True, default=0)),
                ('kredit_13_18', models.FloatField(blank=True, default=0)),
                ('kredit_19_24', models.FloatField(blank=True, default=0)),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(blank=True, default=0, null=True)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('komandaya_gore_prim', models.FloatField(blank=True, default=0)),
                ('fix_maas', models.FloatField(blank=True, default=0)),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasserPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(blank=True, default=0, null=True)),
                ('satis0', models.FloatField(blank=True, default=0)),
                ('satis1_8', models.FloatField(blank=True, default=0)),
                ('satis9_14', models.FloatField(blank=True, default=0)),
                ('satis15p', models.FloatField(blank=True, default=0)),
                ('satis20p', models.FloatField(blank=True, default=0)),
                ('komandaya_gore_prim', models.FloatField(blank=True, default=0)),
                ('ofise_gore_prim', models.FloatField(blank=True, default=0)),
                ('fix_maas', models.FloatField(blank=True, default=0)),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('qeyd', models.TextField(blank=True, default='')),
                ('bonus_tarixi', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_bonus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('yarim_ay_emek_haqqi', models.PositiveBigIntegerField(blank=True, default=0)),
                ('qeyd', models.TextField(blank=True, default='')),
                ('avans_tarixi', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('isci', models.ManyToManyField(related_name='isci_avans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
