# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avans',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_avans', 'Mövcud avanslara baxa bilər'), ('add_avans', 'Avans əlavə edə bilər'), ('change_avans', 'Avans məlumatlarını yeniləyə bilər'), ('delete_avans', 'Avans silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_bonus', 'Mövcud bonuslara baxa bilər'), ('add_bonus', 'Bonus əlavə edə bilər'), ('change_bonus', 'Bonus məlumatlarını yeniləyə bilər'), ('delete_bonus', 'Bonus silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='canvasserprim',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_canvasserprim', 'Mövcud canvasser primlərə baxa bilər'), ('add_canvasserprim', 'Canvasser prim əlavə edə bilər'), ('change_canvasserprim', 'Canvasser prim məlumatlarını yeniləyə bilər'), ('delete_canvasserprim', 'Canvasser prim silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='dealerprim',
            options={'default_permissions': [], 'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='dealerprimnew',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_dealerprimnew', 'Mövcud dealer primlərə baxa bilər'), ('add_dealerprimnew', 'Dealer prim əlavə edə bilər'), ('change_dealerprimnew', 'Dealer prim məlumatlarını yeniləyə bilər'), ('delete_dealerprimnew', 'Dealer prim silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='kesinti',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_kesinti', 'Mövcud kəsintilərə baxa bilər'), ('add_kesinti', 'Kəsinti əlavə edə bilər'), ('change_kesinti', 'Kəsinti məlumatlarını yeniləyə bilər'), ('delete_kesinti', 'Kəsinti silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='kreditorprim',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_kreditorprim', 'Mövcud kreditor primlərə baxa bilər'), ('add_kreditorprim', 'Kreditor prim əlavə edə bilər'), ('change_kreditorprim', 'Kreditor prim məlumatlarını yeniləyə bilər'), ('delete_kreditorprim', 'Kreditor prim silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='maasgoruntuleme',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_maasgoruntuleme', 'Mövcud maaş cədvəllərinə baxa bilər'), ('add_maasgoruntuleme', 'Maaş cədvəli əlavə edə bilər'), ('change_maasgoruntuleme', 'Maaş cədvəlinin məlumatlarını yeniləyə bilər'), ('delete_maasgoruntuleme', 'Maaş cədvəlini silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='maasode',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_maasode', 'Mövcud maaş ödəmələrinə baxa bilər'), ('add_maasode', 'Maaş ödəmə əlavə edə bilər'), ('change_maasode', 'Maaş ödəmə məlumatlarını yeniləyə bilər'), ('delete_maasode', 'Maaş ödəmə silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='officeleaderprim',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_officeleaderprim', 'Mövcud office leader primlərə baxa bilər'), ('add_officeleaderprim', 'Office Leader prim əlavə edə bilər'), ('change_officeleaderprim', 'Office Leader prim məlumatlarını yeniləyə bilər'), ('delete_officeleaderprim', 'Office Leader prim silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='vanleaderprim',
            options={'default_permissions': [], 'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='vanleaderprimnew',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_vanleaderprimnew', 'Mövcud vanleader primlərə baxa bilər'), ('add_vanleaderprimnew', 'Vanleader prim əlavə edə bilər'), ('change_vanleaderprimnew', 'Vanleader prim məlumatlarını yeniləyə bilər'), ('delete_vanleaderprimnew', 'Vanleader prim silə bilər'))},
        ),
    ]
