# Generated by Django 4.0.7 on 2022-10-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_givencommissionaftersigncontract_delete_creditorprim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='givencommissionaftersigncontract',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
