# Generated by Django 4.0.7 on 2022-11-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0015_salaryview_salary_sala_employe_aa6d9b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salaryview',
            name='salary_sala_employe_aa6d9b_idx',
        ),
    ]
