# Generated by Django 4.0.7 on 2022-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0016_remove_salaryview_salary_sala_employe_aa6d9b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryview',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
