# Generated by Django 4.0.7 on 2022-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_salaryview_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='paysalary',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='salarydeduction',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='salarypunishment',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='salaryview',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
