# Generated by Django 4.0.7 on 2022-11-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0019_advancepayment_is_done_bonus_is_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancepayment',
            old_name='is_done',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='bonus',
            old_name='is_done',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='paysalary',
            old_name='is_done',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='salarydeduction',
            old_name='is_done',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='salarypunishment',
            old_name='is_done',
            new_name='is_paid',
        ),
        migrations.AddField(
            model_name='salaryview',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
