# Generated by Django 4.0.7 on 2022-11-17 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0024_remove_salaryviewexport_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryviewexport',
            name='export_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
