# Generated by Django 4.0.7 on 2022-12-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0033_alter_salaryview_final_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryview',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_salaryview', 'Mövcud maaş cədvəllərinə baxa bilər'), ('add_salaryview', 'Maaş cədvəli əlavə edə bilər'), ('change_salaryview', 'Maaş cədvəlinin məlumatlarını yeniləyə bilər'), ('delete_salaryview', 'Maaş cədvəlini silə bilər'))},
        ),
    ]
