# Generated by Django 3.2.12 on 2022-09-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirketKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField(default=0)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa', to='company.shirket')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_shirketkassa', 'Mövcud şirkət kassalara baxa bilər'), ('add_shirketkassa', 'Şirkət kassa əlavə edə bilər'), ('change_shirketkassa', 'Şirkət kassa məlumatlarını yeniləyə bilər'), ('delete_shirketkassa', 'Şirkət kassa silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PulAxini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarix', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('aciqlama', models.TextField(blank=True, null=True)),
                ('ilkin_balans', models.FloatField(default=0)),
                ('sonraki_balans', models.FloatField(default=0)),
                ('holding_ilkin_balans', models.FloatField(default=0)),
                ('holding_sonraki_balans', models.FloatField(default=0)),
                ('shirket_ilkin_balans', models.FloatField(default=0)),
                ('shirket_sonraki_balans', models.FloatField(default=0)),
                ('ofis_ilkin_balans', models.FloatField(default=0)),
                ('ofis_sonraki_balans', models.FloatField(default=0)),
                ('emeliyyat_uslubu', models.CharField(blank=True, choices=[('MƏDAXİL', 'MƏDAXİL'), ('MƏXARİC', 'MƏXARİC'), ('TRANSFER', 'TRANSFER')], default=None, max_length=100, null=True)),
                ('miqdar', models.FloatField(default=0)),
                ('emeliyyat_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pul_axinlari', to=settings.AUTH_USER_MODEL)),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pul_axinlari', to='company.holding')),
                ('ofis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.ofis')),
                ('shirket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pul_axinlari', to='company.shirket')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_pulaxini', 'Mövcud pul axınlarına baxa bilər'), ('add_pulaxini', 'Pul axını əlavə edə bilər'), ('change_pulaxini', 'Pul axını məlumatlarını yeniləyə bilər'), ('delete_pulaxini', 'Pul axını məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OfisKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField(default=0)),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa', to='company.ofis')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_ofiskassa', 'Mövcud ofis kassalara baxa bilər'), ('add_ofiskassa', 'Ofis kassa əlavə edə bilər'), ('change_ofiskassa', 'Ofis kassa məlumatlarını yeniləyə bilər'), ('delete_ofiskassa', 'Ofis kassa silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField(default=0)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa', to='company.holding')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_holdingkassa', 'Mövcud holdinq kassalara baxa bilər'), ('add_holdingkassa', 'Holdinq kassa əlavə edə bilər'), ('change_holdingkassa', 'Holdinq kassa məlumatlarını yeniləyə bilər'), ('delete_holdingkassa', 'Holdinq kassa silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
