# Generated by Django 3.2.12 on 2022-07-29 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VezifePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vezife_permission', to='auth.group')),
                ('vezife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vezife_permission', to='company.vezifeler')),
            ],
        ),
        migrations.CreateModel(
            name='ShirketKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField(default=0)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa', to='company.shirket')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PulAxini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarix', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('aciqlama', models.TextField(blank=True, null=True)),
                ('ilkin_balans', models.FloatField(default=0)),
                ('sonraki_balans', models.FloatField(default=0)),
                ('holding_ilkin_balans', models.FloatField(default=0)),
                ('holding_sonraki_balans', models.FloatField(default=0)),
                ('shirket_ilkin_balans', models.FloatField(default=0)),
                ('shirket_sonraki_balans', models.FloatField(default=0)),
                ('ofis_ilkin_balans', models.FloatField(default=0)),
                ('ofis_sonraki_balans', models.FloatField(default=0)),
                ('emeliyyat_uslubu', models.CharField(blank=True, choices=[('MƏDAXİL', 'MƏDAXİL'), ('MƏXARİC', 'MƏXARİC'), ('TRANSFER', 'TRANSFER')], default=None, max_length=100, null=True)),
                ('miqdar', models.FloatField(default=0)),
                ('emeliyyat_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pul_axinlari', to=settings.AUTH_USER_MODEL)),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pul_axinlari', to='company.holding')),
                ('ofis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.ofis')),
                ('shirket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pul_axinlari', to='company.shirket')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField(default=0)),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa', to='company.ofis')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='HoldingKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField(default=0)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa', to='company.holding')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
