# Generated by Django 3.2.12 on 2022-07-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VezifePermission',
        ),
    ]
