# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_delete_vezifepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingkassa',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_holdingkassa', 'Mövcud holdinq kassalara baxa bilər'), ('add_holdingkassa', 'Holdinq kassa əlavə edə bilər'), ('change_holdingkassa', 'Holdinq kassa məlumatlarını yeniləyə bilər'), ('delete_holdingkassa', 'Holdinq kassa silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='ofiskassa',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_ofiskassa', 'Mövcud ofis kassalara baxa bilər'), ('add_ofiskassa', 'Ofis kassa əlavə edə bilər'), ('change_ofiskassa', 'Ofis kassa məlumatlarını yeniləyə bilər'), ('delete_ofiskassa', 'Ofis kassa silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='pulaxini',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_pulaxini', 'Mövcud pul axınlarına baxa bilər'), ('add_pulaxini', 'Pul axını əlavə edə bilər'), ('change_pulaxini', 'Pul axını məlumatlarını yeniləyə bilər'), ('delete_pulaxini', 'Pul axını məlumatlarını silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirketkassa',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_shirketkassa', 'Mövcud şirkət kassalara baxa bilər'), ('add_shirketkassa', 'Şirkət kassa əlavə edə bilər'), ('change_shirketkassa', 'Şirkət kassa məlumatlarını yeniləyə bilər'), ('delete_shirketkassa', 'Şirkət kassa silə bilər'))},
        ),
    ]
