# Generated by Django 4.0.7 on 2022-11-05 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_section_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0004_holdingcashboxoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingcashboxoperation',
            name='previous_balance',
        ),
        migrations.RemoveField(
            model_name='holdingcashboxoperation',
            name='subsequent_balance',
        ),
        migrations.AddField(
            model_name='holdingcashboxoperation',
            name='operation',
            field=models.CharField(choices=[('MƏDAXİL', 'MƏDAXİL'), ('MƏXARİC', 'MƏXARİC'), ('TRANSFER', 'TRANSFER')], default='MƏDAXİL', max_length=150),
        ),
        migrations.AlterField(
            model_name='holdingcashboxoperation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='OfficeCashboxOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('operation', models.CharField(choices=[('MƏDAXİL', 'MƏDAXİL'), ('MƏXARİC', 'MƏXARİC'), ('TRANSFER', 'TRANSFER')], default='MƏDAXİL', max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cashbox_operations', to='company.company')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cashbox_operations', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cashbox_operations', to='company.office')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_officecashboxoperation', 'Mövcud ofis kassa əməliyyatlarına baxa bilər'), ('add_officecashboxoperation', 'Ofis kassa əməliyyatı əlavə edə bilər'), ('change_officecashboxoperation', 'Ofis kassa əməliyyatı məlumatlarını yeniləyə bilər'), ('delete_officecashboxoperation', 'Ofis kassa əməliyyatı məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
