# Generated by Django 4.0.7 on 2022-11-20 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0008_companycashbox_note_companycashbox_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_personals', to=settings.AUTH_USER_MODEL),
        ),
    ]
