# Generated by Django 4.0.7 on 2022-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0012_alter_cashflow_balance_alter_companycashbox_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
