# Generated by Django 3.2.12 on 2022-09-07 10:37

import core.image_validator
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirketKassaMexaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qebzin_resmi', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('mexaric_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('mexaric_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shirket_mexaric', to=settings.AUTH_USER_MODEL)),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa_mexaric', to='cashbox.shirketkassa')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_shirketkassamexaric', 'Mövcud şirkət kassa məxariclərə baxa bilər'), ('add_shirketkassamexaric', 'Şirkət kassa məxaric əlavə edə bilər'), ('change_shirketkassamexaric', 'Şirkət kassa məxaric məlumatlarını yeniləyə bilər'), ('delete_shirketkassamexaric', 'Şirkət kassa məxaric silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ShirketKassaMedaxil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('medaxil_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('medaxil_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shirket_medaxil', to=settings.AUTH_USER_MODEL)),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa_medaxil', to='cashbox.shirketkassa')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_shirketkassamedaxil', 'Mövcud şirkət kassa mədaxillərə baxa bilər'), ('add_shirketkassamedaxil', 'Şirkət kassa mədaxil əlavə edə bilər'), ('change_shirketkassamedaxil', 'Şirkət kassa mədaxil məlumatlarını yeniləyə bilər'), ('delete_shirketkassamedaxil', 'Şirkət kassa mədaxil silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OfisKassaMexaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qebzin_resmi', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('mexaric_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('mexaric_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ofis_mexaric', to=settings.AUTH_USER_MODEL)),
                ('ofis_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa_mexaric', to='cashbox.ofiskassa')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_ofiskassamexaric', 'Mövcud ofis kassa məxariclərə baxa bilər'), ('add_ofiskassamexaric', 'Ofis kassa məxaric əlavə edə bilər'), ('change_ofiskassamexaric', 'Ofis kassa məxaric məlumatlarını yeniləyə bilər'), ('delete_ofiskassamexaric', 'Ofis kassa məxaric silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OfisKassaMedaxil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('medaxil_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('medaxil_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ofis_medaxil', to=settings.AUTH_USER_MODEL)),
                ('ofis_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa_medaxil', to='cashbox.ofiskassa')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_ofiskassamedaxil', 'Mövcud ofis kassa mədaxillərə baxa bilər'), ('add_ofiskassamedaxil', 'Ofis kassa mədaxil əlavə edə bilər'), ('change_ofiskassamedaxil', 'Ofis kassa mədaxil məlumatlarını yeniləyə bilər'), ('delete_ofiskassamedaxil', 'Ofis kassa mədaxil silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingKassaMexaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qebzin_resmi', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('mexaric_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa_mexaric', to='cashbox.holdingkassa')),
                ('mexaric_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_mexaric', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_holdingkassamexaric', 'Mövcud holdinq kassa məxariclərə baxa bilər'), ('add_holdingkassamexaric', 'Holdinq kassa məxaric əlavə edə bilər'), ('change_holdingkassamexaric', 'Holdinq kassa məxaric məlumatlarını yeniləyə bilər'), ('delete_holdingkassamexaric', 'Holdinq kassa məxaric silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingKassaMedaxil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('medaxil_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa_medaxil', to='cashbox.holdingkassa')),
                ('medaxil_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_medaxil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_holdingkassamedaxil', 'Mövcud holdinq kassa mədaxillərə baxa bilər'), ('add_holdingkassamedaxil', 'Holdinq kassa mədaxil əlavə edə bilər'), ('change_holdingkassamedaxil', 'Holdinq kassa mədaxil məlumatlarını yeniləyə bilər'), ('delete_holdingkassamedaxil', 'Holdinq kassa mədaxil silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
