# Generated by Django 3.2.12 on 2022-07-29 12:19

import core.image_validator
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirketKassaMexaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qebzin_resmi', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('mexaric_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('mexaric_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shirket_mexaric', to=settings.AUTH_USER_MODEL)),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa_mexaric', to='cashbox.shirketkassa')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketKassaMedaxil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('medaxil_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('medaxil_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shirket_medaxil', to=settings.AUTH_USER_MODEL)),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa_medaxil', to='cashbox.shirketkassa')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisKassaMexaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qebzin_resmi', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('mexaric_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('mexaric_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ofis_mexaric', to=settings.AUTH_USER_MODEL)),
                ('ofis_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa_mexaric', to='cashbox.ofiskassa')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisKassaMedaxil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('medaxil_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('medaxil_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ofis_medaxil', to=settings.AUTH_USER_MODEL)),
                ('ofis_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa_medaxil', to='cashbox.ofiskassa')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='HoldingKassaMexaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qebzin_resmi', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('mexaric_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa_mexaric', to='cashbox.holdingkassa')),
                ('mexaric_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_mexaric', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='HoldingKassaMedaxil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0)),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('medaxil_tarixi', models.DateField(default=None)),
                ('evvelki_balans', models.FloatField(blank=True, default=0)),
                ('sonraki_balans', models.FloatField(blank=True, default=0)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa_medaxil', to='cashbox.holdingkassa')),
                ('medaxil_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_medaxil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
