# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingkassamedaxil',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_holdingkassamedaxil', 'Mövcud holdinq kassa mədaxillərə baxa bilər'), ('add_holdingkassamedaxil', 'Holdinq kassa mədaxil əlavə edə bilər'), ('change_holdingkassamedaxil', 'Holdinq kassa mədaxil məlumatlarını yeniləyə bilər'), ('delete_holdingkassamedaxil', 'Holdinq kassa mədaxil silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='holdingkassamexaric',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_holdingkassamexaric', 'Mövcud holdinq kassa məxariclərə baxa bilər'), ('add_holdingkassamexaric', 'Holdinq kassa məxaric əlavə edə bilər'), ('change_holdingkassamexaric', 'Holdinq kassa məxaric məlumatlarını yeniləyə bilər'), ('delete_holdingkassamexaric', 'Holdinq kassa məxaric silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='ofiskassamedaxil',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_ofiskassamedaxil', 'Mövcud ofis kassa mədaxillərə baxa bilər'), ('add_ofiskassamedaxil', 'Ofis kassa mədaxil əlavə edə bilər'), ('change_ofiskassamedaxil', 'Ofis kassa mədaxil məlumatlarını yeniləyə bilər'), ('delete_ofiskassamedaxil', 'Ofis kassa mədaxil silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='ofiskassamexaric',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_ofiskassamexaric', 'Mövcud ofis kassa məxariclərə baxa bilər'), ('add_ofiskassamexaric', 'Ofis kassa məxaric əlavə edə bilər'), ('change_ofiskassamexaric', 'Ofis kassa məxaric məlumatlarını yeniləyə bilər'), ('delete_ofiskassamexaric', 'Ofis kassa məxaric silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirketkassamedaxil',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_shirketkassamedaxil', 'Mövcud şirkət kassa mədaxillərə baxa bilər'), ('add_shirketkassamedaxil', 'Şirkət kassa mədaxil əlavə edə bilər'), ('change_shirketkassamedaxil', 'Şirkət kassa mədaxil məlumatlarını yeniləyə bilər'), ('delete_shirketkassamedaxil', 'Şirkət kassa mədaxil silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='shirketkassamexaric',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_shirketkassamexaric', 'Mövcud şirkət kassa məxariclərə baxa bilər'), ('add_shirketkassamexaric', 'Şirkət kassa məxaric əlavə edə bilər'), ('change_shirketkassamexaric', 'Şirkət kassa məxaric məlumatlarını yeniləyə bilər'), ('delete_shirketkassamexaric', 'Şirkət kassa məxaric silə bilər'))},
        ),
    ]
