# Generated by Django 4.0.7 on 2022-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contractgift_gift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='initial_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_debt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
