# Generated by Django 4.0.7 on 2022-12-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contractchange_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='pay_status_helper',
            field=models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY'), ('RAZILAŞDIRILMIŞ AZ ÖDƏMƏ', 'RAZILAŞDIRILMIŞ AZ ÖDƏMƏ'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ'), ('SON AYIN BÖLÜNMƏSİ', 'SON AYIN BÖLÜNMƏSİ')], default='ÖDƏNMƏYƏN', max_length=200),
        ),
        migrations.AlterField(
            model_name='installment',
            name='overpayment_substatus',
            field=models.CharField(blank=True, choices=[('ARTIQ BİR AY', 'ARTIQ BİR AY'), ('ARTIQ BÜTÜN AYLAR', 'ARTIQ BÜTÜN AYLAR')], default=None, max_length=200, null=True),
        ),
    ]
