# Generated by Django 3.2.9 on 2023-01-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_auto_20221231_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='is_remove',
            new_name='is_holding_contract',
        ),
        migrations.AlterField(
            model_name='contract',
            name='intervention_product_status',
            field=models.CharField(blank=True, choices=[('DƏYİŞİLMİŞ MƏHSUL', 'DƏYİŞİLMİŞ MƏHSUL'), ('SÖKÜNTÜ', 'SÖKÜNTÜ')], default=None, max_length=50, null=True),
        ),
    ]
