# Generated by Django 3.2.9 on 2023-01-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_contract_installment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='close_the_debt_status',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='conditional_payment_status',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='pay_status_helper',
        ),
        migrations.AddField(
            model_name='installment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_status',
            field=models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM ÖDƏMƏ'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ')], default='ÖDƏNMƏYƏN', max_length=30),
        ),
    ]
