# Generated by Django 3.2.9 on 2023-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_auto_20230111_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='close_the_debt_status',
            field=models.CharField(blank=True, choices=[('BORCU BAĞLA', 'BORCU BAĞLA')], default=None, max_length=50, null=True),
        ),
    ]
