# Generated by Django 3.2.9 on 2023-01-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_installment_close_the_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='payment_status',
            field=models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM ÖDƏMƏ', 'NATAMAM ÖDƏMƏ'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ')], default='ÖDƏNMƏYƏN', max_length=30),
        ),
    ]
