# Generated by Django 3.2.9 on 2023-01-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_remove_installment_overpayment_substatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='new_graphic_status',
            field=models.CharField(blank=True, choices=[('ARTIRMAQ', 'ARTIRMAQ'), ('AZALTMAQ', 'AZALTMAQ')], default=None, max_length=50, null=True),
        ),
    ]
