# Generated by Django 3.2.9 on 2023-01-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_alter_contract_new_graphic_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractChange',
        ),
    ]
