# Generated by Django 3.2.9 on 2023-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_delete_contractchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_debt_status',
            field=models.CharField(blank=True, choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_status',
            field=models.CharField(blank=True, choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20),
        ),
    ]
