# Generated by Django 3.2.9 on 2023-01-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_auto_20230112_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_debt_status',
            field=models.CharField(blank=True, choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_status',
            field=models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='BİTMİŞ', max_length=20),
        ),
    ]
