# Generated by Django 3.2.9 on 2023-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_remove_contract_pdf2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
