# Generated by Django 3.2.9 on 2023-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0030_auto_20230130_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_debt_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
