# Generated by Django 3.2.9 on 2023-02-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0031_auto_20230131_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractgift',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_contractgift', 'Mövcud müqavilə hədiyyələrə baxa bilər'), ('add_contractgift', "Müqaviləy' hədiyyə əlavə edə bilər"), ('change_contractgift', 'Müqavilənin hədiyyə məlumatlarını yeniləyə bilər'), ('delete_contractgift', 'Müqavilənin hədiyyəsini silə bilər'))},
        ),
    ]
