# Generated by Django 3.2.9 on 2023-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_alter_contractgift_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='remaining_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
