# Generated by Django 3.2.9 on 2023-02-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0033_installment_remaining_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
