# Generated by Django 3.2.9 on 2023-02-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0034_contract_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='old_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_contracts', to='contract.contract'),
        ),
    ]
