# Generated by Django 3.2.9 on 2023-02-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0035_contract_old_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='changed_new_contract',
            field=models.BooleanField(default=False),
        ),
    ]
