# Generated by Django 3.2.9 on 2023-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0036_contract_changed_new_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='compensation_expense',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='compensation_income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='default_installment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_debt',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='new_graphic_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paid_initial_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paid_initial_payment_debt',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remaining_debt',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='remaining_debt',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
    ]
