# Generated by Django 3.2.12 on 2022-09-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_anbar', to='company.ofis')),
                ('shirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_anbar', to='company.shirket')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_anbar', 'Mövcud anbarlara baxa bilər'), ('add_anbar', 'Anbar əlavə edə bilər'), ('change_anbar', 'Anbar məlumatlarını yeniləyə bilər'), ('delete_anbar', 'Anbar silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.IntegerField(default=0)),
                ('tarix', models.DateField(auto_now=True)),
                ('qeyd', models.TextField(blank=True, default='', null=True)),
                ('anbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.anbar')),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mehsullar')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_stok', 'Mövcud stoklara baxa bilər'), ('add_stok', 'Stok əlavə edə bilər'), ('change_stok', 'Stok məlumatlarını yeniləyə bilər'), ('delete_stok', 'Stok silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Emeliyyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsul_ve_sayi', models.CharField(blank=True, max_length=500, null=True)),
                ('qeyd', models.TextField(blank=True, default='', null=True)),
                ('emeliyyat_tarixi', models.DateField(auto_now_add=True, null=True)),
                ('emeliyyat_novu', models.CharField(choices=[('transfer', 'transfer'), ('stok yeniləmə', 'stok yeniləmə')], default='transfer', max_length=50)),
                ('say', models.IntegerField(blank=True, default=0, null=True)),
                ('gonderen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gonderen', to='warehouse.anbar')),
                ('icraci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emeliyyat', to=settings.AUTH_USER_MODEL)),
                ('qebul_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qebul_eden', to='warehouse.anbar')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_emeliyyat', 'Mövcud əməliyyatlara baxa bilər'), ('add_emeliyyat', 'Əməliyyat əlavə edə bilər'), ('change_emeliyyat', 'Əməliyyat məlumatlarını yeniləyə bilər'), ('delete_emeliyyat', 'Əməliyyat silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='AnbarQeydler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsul_ve_sayi', models.CharField(blank=True, max_length=250, null=True)),
                ('qeyd', models.TextField()),
                ('yerine_yetirildi', models.BooleanField(default=False)),
                ('gonderilme_tarixi', models.DateField(auto_now_add=True)),
                ('anbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anbar_qeyd', to='warehouse.anbar')),
                ('gonderen_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anbar_sorgu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_anbarqeydler', 'Mövcud anbar sorğularına baxa bilər'), ('add_anbarqeydler', 'Anbar sorğu əlavə edə bilər'), ('change_anbarqeydler', 'Anbar sorğu məlumatlarını yeniləyə bilər'), ('delete_anbarqeydler', 'Anbar sorğu silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
