# Generated by Django 3.2.12 on 2022-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anbar',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_anbar', 'Mövcud anbarlara baxa bilər'), ('add_anbar', 'Anbar əlavə edə bilər'), ('change_anbar', 'Anbar məlumatlarını yeniləyə bilər'), ('delete_anbar', 'Anbar silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='anbarqeydler',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_anbarqeydler', 'Mövcud anbar sorğularına baxa bilər'), ('add_anbarqeydler', 'Anbar sorğu əlavə edə bilər'), ('change_anbarqeydler', 'Anbar sorğu məlumatlarını yeniləyə bilər'), ('delete_anbarqeydler', 'Anbar sorğu silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='emeliyyat',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_emeliyyat', 'Mövcud əməliyyatlara baxa bilər'), ('add_emeliyyat', 'Əməliyyat əlavə edə bilər'), ('change_emeliyyat', 'Əməliyyat məlumatlarını yeniləyə bilər'), ('delete_emeliyyat', 'Əməliyyat silə bilər'))},
        ),
        migrations.AlterModelOptions(
            name='stok',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_stok', 'Mövcud stoklara baxa bilər'), ('add_stok', 'Stok əlavə edə bilər'), ('change_stok', 'Stok məlumatlarını yeniləyə bilər'), ('delete_stok', 'Stok silə bilər'))},
        ),
    ]
