# Generated by Django 3.2.12 on 2022-08-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20220811_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='tarix',
            field=models.DateField(auto_now=True),
        ),
    ]
