# Generated by Django 4.0.7 on 2022-09-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_stock_product_alter_stock_warehouse'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='unique name for your constraint',
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique name for your stock constraint'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('name', 'office'), name='unique name for your warehouse constraint'),
        ),
    ]
