# Generated by Django 3.2.12 on 2022-08-18 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0004_stok_qeyd'),
    ]

    operations = [
        migrations.AddField(
            model_name='emeliyyat',
            name='emeliyyat_novu',
            field=models.CharField(choices=[('transfer', 'transfer'), ('stok yeniləmə', 'stok yeniləmə')], default='transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='emeliyyat',
            name='icraci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emeliyyat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emeliyyat',
            name='say',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
