# Generated by Django 3.2.12 on 2022-08-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20220818_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emeliyyat',
            name='emeliyyat_tarixi',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
